/*
###############################################################
#  Generated by:      Cadence Innovus 18.11-s100_1
#  OS:                Linux x86_64(Host ID soc05)
#  Generated on:      Sun Oct 24 18:53:17 2021
#  Design:            LBP_CHIP
#  Command:           saveNetlist LBP_CHIP_netlist.v
###############################################################
*/
// Original LBP_syn circuit!
module FSM (
	reset, 
	gray_ready, 
	gray_req, 
	lbp_addr, 
	lbp_valid, 
	gray_count, 
	lbp_count, 
	cycle, 
	initialize, 
	gray_addr_en, 
	lbp_addr_en, 
	finish, 
	clk);
   input reset;
   input gray_ready;
   output gray_req;
   input [13:0] lbp_addr;
   output lbp_valid;
   output [1:0] gray_count;
   output [1:0] lbp_count;
   output [3:0] cycle;
   output initialize;
   output gray_addr_en;
   output lbp_addr_en;
   output finish;
   input clk;

   // Internal wires
   wire FE_RN_1;
   wire N75;
   wire N76;
   wire N79;
   wire N80;
   wire N89;
   wire N92;
   wire n29;
   wire n30;
   wire n31;
   wire n32;
   wire n33;
   wire n34;
   wire n35;
   wire n36;
   wire n37;
   wire n38;
   wire n39;
   wire n40;
   wire n41;
   wire n42;
   wire n43;
   wire n44;
   wire n45;
   wire n46;
   wire n47;
   wire n48;
   wire n49;
   wire n50;
   wire n51;
   wire n52;
   wire n53;
   wire n54;
   wire n55;
   wire n56;
   wire n57;
   wire n58;
   wire n59;
   wire n60;
   wire n61;
   wire n62;
   wire n63;
   wire n64;
   wire n65;
   wire n66;
   wire n67;
   wire n68;
   wire n69;
   wire n70;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire n10;
   wire n11;
   wire n12;
   wire n13;
   wire n14;
   wire n15;
   wire n16;
   wire n17;
   wire n18;
   wire [2:0] cs;
   wire [2:0] ns;

   assign gray_addr_en = N89 ;
   assign FE_RN_1 = N92 ;
   assign lbp_valid = FE_RN_1 ;

   ND2 U60 (.O(n30),
	.I1(n8),
	.I2(n31));
   ND2 U61 (.O(n29),
	.I1(lbp_count[0]),
	.I2(n6));
   OA112 U62 (.O(n34),
	.A1(n36),
	.B1(n4),
	.C1(n35),
	.C2(n10));
   OA13S U63 (.O(n35),
	.A1(n7),
	.B1(n37),
	.B2(n38),
	.B3(n39));
   AN3B2S U64 (.O(n42),
	.I1(n43),
	.B1(lbp_addr[5]),
	.B2(lbp_addr[4]));
   AN2 U65 (.O(n44),
	.I1(lbp_addr[10]),
	.I2(lbp_addr[0]));
   AN3B2S U66 (.O(n54),
	.I1(gray_ready),
	.B1(cs[0]),
	.B2(cs[1]));
   ND2 U67 (.O(n52),
	.I1(cycle[1]),
	.I2(cycle[0]));
   ND2 U68 (.O(n36),
	.I1(cs[0]),
	.I2(n11));
   ND2 U69 (.O(n53),
	.I1(n64),
	.I2(n10));
   ND2 U70 (.O(n32),
	.I1(cs[1]),
	.I2(n7));
   ND2 U71 (.O(n49),
	.I1(cs[2]),
	.I2(n64));
   QDFFRBN \cs_reg[1]  (.Q(cs[1]),
	.D(ns[1]),
	.CK(clk),
	.RB(n18));
   QDFFRBN \lbp_count_reg[1]  (.Q(lbp_count[1]),
	.D(N80),
	.CK(clk),
	.RB(n18));
   QDFFRBN \cs_reg[0]  (.Q(cs[0]),
	.D(ns[0]),
	.CK(clk),
	.RB(n18));
   QDFFRBN \gray_count_reg[0]  (.Q(gray_count[0]),
	.D(N75),
	.CK(clk),
	.RB(n18));
   QDFFRBN \gray_count_reg[1]  (.Q(gray_count[1]),
	.D(N76),
	.CK(clk),
	.RB(n18));
   QDFFRBN \cs_reg[2]  (.Q(cs[2]),
	.D(ns[2]),
	.CK(clk),
	.RB(n18));
   QDFFRBN \lbp_count_reg[0]  (.Q(lbp_count[0]),
	.D(N79),
	.CK(clk),
	.RB(n18));
   QDFFRBN \cycle_reg[2]  (.Q(cycle[2]),
	.D(n68),
	.CK(clk),
	.RB(n18));
   QDFFRBN \cycle_reg[3]  (.Q(cycle[3]),
	.D(n67),
	.CK(clk),
	.RB(n18));
   QDFFRBN \cycle_reg[1]  (.Q(cycle[1]),
	.D(n69),
	.CK(clk),
	.RB(n18));
   QDFFRBN \cycle_reg[0]  (.Q(cycle[0]),
	.D(n70),
	.CK(clk),
	.RB(n18));
   QDFFN finish_reg (.Q(finish),
	.D(n5),
	.CK(clk));
   OA12 U4 (.O(gray_req),
	.A1(n8),
	.B1(cycle[3]),
	.B2(n51));
   INV1S U5 (.O(n6),
	.I(n53));
   INV1S U6 (.O(n8),
	.I(n36));
   NR2 U7 (.O(n64),
	.I1(n11),
	.I2(n7));
   ND3 U8 (.O(n51),
	.I1(n15),
	.I2(n16),
	.I3(n12));
   NR2 U9 (.O(N89),
	.I1(n10),
	.I2(n36));
   AOI12HS U10 (.O(n33),
	.A1(N79),
	.B1(n9),
	.B2(n6));
   OAI22S U11 (.O(n67),
	.A1(n55),
	.A2(n56),
	.B1(n8),
	.B2(n17));
   XOR2HS U12 (.O(n56),
	.I1(n17),
	.I2(n57));
   NR2 U13 (.O(n57),
	.I1(n52),
	.I2(n16));
   ND3 U14 (.O(n31),
	.I1(n16),
	.I2(n17),
	.I3(n52));
   INV1S U15 (.O(n14),
	.I(n52));
   INV1S U16 (.O(n3),
	.I(n32));
   INV1S U17 (.O(n5),
	.I(n49));
   NR2P U18 (.O(initialize),
	.I1(cs[2]),
	.I2(n64));
   INV1S U19 (.O(n16),
	.I(cycle[2]));
   INV1S U20 (.O(n12),
	.I(cycle[0]));
   INV1S U21 (.O(n15),
	.I(cycle[1]));
   INV1S U22 (.O(n7),
	.I(cs[0]));
   INV1S U23 (.O(n11),
	.I(cs[1]));
   INV1S U24 (.O(n10),
	.I(cs[2]));
   ND3 U25 (.O(ns[0]),
	.I1(n45),
	.I2(n33),
	.I3(n46));
   AN4B1S U26 (.O(n46),
	.I1(n47),
	.I2(n48),
	.I3(n49),
	.B1(N92));
   AOI13HS U27 (.O(n45),
	.A1(n54),
	.B1(n3),
	.B2(gray_count[0]),
	.B3(gray_count[1]));
   ND3 U28 (.O(n48),
	.I1(n50),
	.I2(n51),
	.I3(cycle[3]));
   AOI22S U29 (.O(n55),
	.A1(n13),
	.A2(n50),
	.B1(N89),
	.B2(n62));
   INV1S U30 (.O(n13),
	.I(n63));
   ND3 U31 (.O(n62),
	.I1(n16),
	.I2(n17),
	.I3(n14));
   AN4B1S U32 (.O(n63),
	.I1(n15),
	.I2(cycle[0]),
	.I3(n16),
	.B1(n17));
   ND3 U33 (.O(n39),
	.I1(n40),
	.I2(n41),
	.I3(n42));
   NR2 U34 (.O(n40),
	.I1(lbp_addr[1]),
	.I2(cs[1]));
   NR2 U35 (.O(n41),
	.I1(lbp_addr[3]),
	.I2(lbp_addr[2]));
   INV1S U36 (.O(n17),
	.I(cycle[3]));
   OAI22S U37 (.O(n70),
	.A1(cycle[0]),
	.A2(n55),
	.B1(n8),
	.B2(n12));
   NR2 U38 (.O(n50),
	.I1(n36),
	.I2(cs[2]));
   NR2 U39 (.O(N75),
	.I1(n32),
	.I2(gray_count[0]));
   INV1S U40 (.O(n9),
	.I(lbp_count[1]));
   NR2 U41 (.O(N79),
	.I1(n53),
	.I2(lbp_count[0]));
   MOAI1S U42 (.O(n69),
	.A1(n60),
	.A2(n15),
	.B1(n61),
	.B2(cycle[0]));
   NR2 U43 (.O(n60),
	.I1(n12),
	.I2(n36));
   NR2 U44 (.O(n61),
	.I1(cycle[1]),
	.I2(n55));
   MOAI1S U45 (.O(ns[2]),
	.A1(n9),
	.A2(n29),
	.B1(cs[2]),
	.B2(n30));
   NR2 U46 (.O(N76),
	.I1(n66),
	.I2(n32));
   XNR2HS U47 (.O(n66),
	.I1(gray_count[0]),
	.I2(gray_count[1]));
   NR2 U48 (.O(n43),
	.I1(lbp_addr[7]),
	.I2(lbp_addr[6]));
   OAI112HS U49 (.O(ns[1]),
	.A1(n33),
	.B1(n34),
	.C1(gray_count[1]),
	.C2(n32));
   INV1S U50 (.O(n4),
	.I(N75));
   NR2 U51 (.O(N80),
	.I1(n65),
	.I2(n53));
   XOR2HS U52 (.O(n65),
	.I1(lbp_count[0]),
	.I2(n9));
   ND3 U53 (.O(n47),
	.I1(cs[0]),
	.I2(n31),
	.I3(cs[2]));
   MOAI1S U54 (.O(n68),
	.A1(n58),
	.A2(n16),
	.B1(n59),
	.B2(n14));
   NR2 U55 (.O(n58),
	.I1(n36),
	.I2(n52));
   NR2 U56 (.O(n59),
	.I1(cycle[2]),
	.I2(n55));
   ND3 U57 (.O(n38),
	.I1(lbp_addr[8]),
	.I2(lbp_addr[13]),
	.I3(lbp_addr[9]));
   ND3 U58 (.O(n37),
	.I1(lbp_addr[12]),
	.I2(lbp_addr[11]),
	.I3(n44));
   INV1S U59 (.O(n18),
	.I(reset));
   NR3H U73 (.O(N92),
	.I1(cs[0]),
	.I2(cs[1]),
	.I3(n10));
endmodule

module GAC_DW01_inc_0 (
	A, 
	SUM);
   input [6:0] A;
   output [6:0] SUM;

   // Internal wires
   wire [6:2] carry;

   HA1 U1_1_5 (.S(SUM[5]),
	.C(carry[6]),
	.A(A[5]),
	.B(carry[5]));
   HA1 U1_1_4 (.S(SUM[4]),
	.C(carry[5]),
	.A(A[4]),
	.B(carry[4]));
   HA1 U1_1_3 (.S(SUM[3]),
	.C(carry[4]),
	.A(A[3]),
	.B(carry[3]));
   HA1 U1_1_2 (.S(SUM[2]),
	.C(carry[3]),
	.A(A[2]),
	.B(carry[2]));
   HA1 U1_1_1 (.S(SUM[1]),
	.C(carry[2]),
	.A(A[1]),
	.B(A[0]));
   XOR2HS U1 (.O(SUM[6]),
	.I1(carry[6]),
	.I2(A[6]));
   INV1S U2 (.O(SUM[0]),
	.I(A[0]));
endmodule

module GAC_DW01_inc_1 (
	A, 
	SUM, 
	p1);
   input [6:0] A;
   output [6:0] SUM;
   input p1;

   // Internal wires
   wire [6:2] carry;

   assign SUM[0] = p1 ;

   HA1 U1_1_5 (.S(SUM[5]),
	.C(carry[6]),
	.A(A[5]),
	.B(carry[5]));
   HA1 U1_1_4 (.S(SUM[4]),
	.C(carry[5]),
	.A(A[4]),
	.B(carry[4]));
   HA1 U1_1_3 (.S(SUM[3]),
	.C(carry[4]),
	.A(A[3]),
	.B(carry[3]));
   HA1 U1_1_2 (.S(SUM[2]),
	.C(carry[3]),
	.A(A[2]),
	.B(carry[2]));
   HA1 U1_1_1 (.S(SUM[1]),
	.C(carry[2]),
	.A(A[1]),
	.B(A[0]));
   XOR2HS U1 (.O(SUM[6]),
	.I1(carry[6]),
	.I2(A[6]));
endmodule

module GAC_DW01_add_1 (
	A, 
	B, 
	SUM);
   input [6:0] A;
   input [6:0] B;
   output [6:0] SUM;

   // Internal wires
   wire n1;
   wire [6:1] carry;

   FA1S U1_2 (.S(SUM[2]),
	.CO(carry[3]),
	.A(A[2]),
	.B(B[2]),
	.CI(carry[2]));
   FA1S U1_3 (.S(SUM[3]),
	.CO(carry[4]),
	.A(A[3]),
	.B(B[3]),
	.CI(carry[3]));
   FA1S U1_1 (.S(SUM[1]),
	.CO(carry[2]),
	.A(A[1]),
	.B(B[1]),
	.CI(n1));
   FA1S U1_5 (.S(SUM[5]),
	.CO(carry[6]),
	.A(A[5]),
	.B(B[5]),
	.CI(carry[5]));
   FA1S U1_4 (.S(SUM[4]),
	.CO(carry[5]),
	.A(A[4]),
	.B(B[4]),
	.CI(carry[4]));
   XOR3 U1_6 (.O(SUM[6]),
	.I1(A[6]),
	.I2(B[6]),
	.I3(carry[6]));
   AN2 U1 (.O(n1),
	.I1(B[0]),
	.I2(A[0]));
   XOR2HS U2 (.O(SUM[0]),
	.I1(B[0]),
	.I2(A[0]));
endmodule

module GAC_DW01_add_0 (
	A, 
	B, 
	SUM);
   input [6:0] A;
   input [6:0] B;
   output [6:0] SUM;

   // Internal wires
   wire n1;
   wire [6:1] carry;

   XOR3 U1_6 (.O(SUM[6]),
	.I1(A[6]),
	.I2(B[6]),
	.I3(carry[6]));
   FA1S U1_3 (.S(SUM[3]),
	.CO(carry[4]),
	.A(A[3]),
	.B(B[3]),
	.CI(carry[3]));
   FA1S U1_1 (.S(SUM[1]),
	.CO(carry[2]),
	.A(A[1]),
	.B(B[1]),
	.CI(n1));
   FA1S U1_2 (.S(SUM[2]),
	.CO(carry[3]),
	.A(A[2]),
	.B(B[2]),
	.CI(carry[2]));
   FA1S U1_5 (.S(SUM[5]),
	.CO(carry[6]),
	.A(A[5]),
	.B(B[5]),
	.CI(carry[5]));
   FA1S U1_4 (.S(SUM[4]),
	.CO(carry[5]),
	.A(A[4]),
	.B(B[4]),
	.CI(carry[4]));
   AN2 U1 (.O(n1),
	.I1(B[0]),
	.I2(A[0]));
   XOR2HS U2 (.O(SUM[0]),
	.I1(B[0]),
	.I2(A[0]));
endmodule

module GAC (
	reset, 
	gray_addr, 
	lbp_addr, 
	cycle, 
	gray_addr_en, 
	initialize, 
	fill_right, 
	fill_down, 
	fill_left, 
	clk);
   input reset;
   output [13:0] gray_addr;
   input [13:0] lbp_addr;
   input [3:0] cycle;
   input gray_addr_en;
   input initialize;
   input fill_right;
   input fill_down;
   input fill_left;
   input clk;

   // Internal wires
   wire FE_DBTN0_lbp_addr_0;
   wire N63;
   wire N64;
   wire N65;
   wire N66;
   wire N67;
   wire N68;
   wire N69;
   wire N70;
   wire N71;
   wire N72;
   wire N73;
   wire N74;
   wire N75;
   wire N76;
   wire N93;
   wire N94;
   wire N95;
   wire N96;
   wire N97;
   wire N98;
   wire N100;
   wire N101;
   wire N102;
   wire N103;
   wire N104;
   wire N105;
   wire N106;
   wire N114;
   wire N115;
   wire N116;
   wire N117;
   wire N118;
   wire N119;
   wire N120;
   wire n16;
   wire n17;
   wire n18;
   wire n19;
   wire n20;
   wire n21;
   wire n22;
   wire n23;
   wire n24;
   wire n25;
   wire n26;
   wire n27;
   wire n28;
   wire n29;
   wire n30;
   wire n31;
   wire n32;
   wire n33;
   wire n34;
   wire n35;
   wire n36;
   wire n37;
   wire n38;
   wire n39;
   wire n40;
   wire n41;
   wire n42;
   wire n43;
   wire n44;
   wire n45;
   wire n46;
   wire n47;
   wire n48;
   wire n49;
   wire n50;
   wire n51;
   wire n52;
   wire n53;
   wire n54;
   wire n55;
   wire n56;
   wire n57;
   wire n58;
   wire n59;
   wire N108;
   wire N62;
   wire N59;
   wire N58;
   wire N57;
   wire n1;
   wire n3;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n10;
   wire n11;
   wire n12;
   wire n13;
   wire n14;
   wire n15;
   wire n60;
   wire n61;
   wire n62;
   wire n63;
   wire n64;
   wire n65;
   wire n66;
   wire n67;
   wire n68;
   wire n69;
   wire n70;
   wire [6:0] gray_addr_row;
   wire [6:0] gray_addr_col;

   INV1S FE_DBTC0_lbp_addr_0 (.O(FE_DBTN0_lbp_addr_0),
	.I(lbp_addr[0]));
   AO222 U37 (.O(n46),
	.A1(N100),
	.A2(n16),
	.B1(N63),
	.B2(n17),
	.C1(gray_addr_row[0]),
	.C2(n18));
   AO222 U38 (.O(n47),
	.A1(N101),
	.A2(n16),
	.B1(N64),
	.B2(n17),
	.C1(gray_addr_row[1]),
	.C2(n18));
   AO222 U39 (.O(n48),
	.A1(N102),
	.A2(n16),
	.B1(N65),
	.B2(n17),
	.C1(gray_addr_row[2]),
	.C2(n18));
   AO222 U40 (.O(n49),
	.A1(N103),
	.A2(n16),
	.B1(N66),
	.B2(n17),
	.C1(gray_addr_row[3]),
	.C2(n18));
   AO222 U41 (.O(n50),
	.A1(N104),
	.A2(n16),
	.B1(N67),
	.B2(n17),
	.C1(gray_addr_row[4]),
	.C2(n18));
   AO222 U42 (.O(n51),
	.A1(N105),
	.A2(n16),
	.B1(N68),
	.B2(n17),
	.C1(gray_addr_row[5]),
	.C2(n18));
   AO222 U43 (.O(n52),
	.A1(N106),
	.A2(n16),
	.B1(N69),
	.B2(n17),
	.C1(gray_addr_row[6]),
	.C2(n18));
   ND2 U44 (.O(n53),
	.I1(n20),
	.I2(n21));
   ND2 U45 (.O(n54),
	.I1(n22),
	.I2(n23));
   ND2 U46 (.O(n55),
	.I1(n24),
	.I2(n25));
   ND2 U47 (.O(n56),
	.I1(n26),
	.I2(n27));
   ND2 U48 (.O(n57),
	.I1(n28),
	.I2(n29));
   ND2 U49 (.O(n58),
	.I1(n30),
	.I2(n31));
   ND2 U50 (.O(n59),
	.I1(n32),
	.I2(n33));
   ND2 U53 (.O(n36),
	.I1(fill_down),
	.I2(gray_addr_en));
   ND2 U54 (.O(n35),
	.I1(gray_addr_en),
	.I2(fill_right));
   ND2 U55 (.O(n34),
	.I1(fill_left),
	.I2(gray_addr_en));
   AN2 U56 (.O(gray_addr[9]),
	.I1(n67),
	.I2(gray_addr_row[2]));
   AO222 U57 (.O(gray_addr[8]),
	.A1(n37),
	.A2(n38),
	.B1(cycle[3]),
	.B2(n39),
	.C1(n67),
	.C2(gray_addr_row[1]));
   AN2 U58 (.O(gray_addr[6]),
	.I1(n67),
	.I2(gray_addr_col[6]));
   AN2 U59 (.O(gray_addr[5]),
	.I1(n67),
	.I2(gray_addr_col[5]));
   AN2 U60 (.O(gray_addr[4]),
	.I1(n67),
	.I2(gray_addr_col[4]));
   AN2 U61 (.O(gray_addr[3]),
	.I1(n67),
	.I2(gray_addr_col[3]));
   AN2 U62 (.O(gray_addr[2]),
	.I1(n67),
	.I2(gray_addr_col[2]));
   AN2 U63 (.O(gray_addr[13]),
	.I1(n67),
	.I2(gray_addr_row[6]));
   AN2 U64 (.O(gray_addr[12]),
	.I1(n67),
	.I2(gray_addr_row[5]));
   AN2 U65 (.O(gray_addr[11]),
	.I1(n67),
	.I2(gray_addr_row[4]));
   AN2 U66 (.O(gray_addr[10]),
	.I1(n67),
	.I2(gray_addr_row[3]));
   ND2 U67 (.O(n45),
	.I1(n43),
	.I2(n68));
   ND2 U68 (.O(n44),
	.I1(cycle[0]),
	.I2(n69));
   AN3B2S U69 (.O(n38),
	.I1(cycle[2]),
	.B1(cycle[3]),
	.B2(n67));
   GAC_DW01_inc_0 add_82 (.A({ lbp_addr[13],
		lbp_addr[12],
		lbp_addr[11],
		lbp_addr[10],
		lbp_addr[9],
		lbp_addr[8],
		lbp_addr[7] }),
	.SUM({ N106,
		N105,
		N104,
		N103,
		N102,
		N101,
		N100 }));
   GAC_DW01_inc_1 add_75 (.A({ lbp_addr[6],
		lbp_addr[5],
		lbp_addr[4],
		lbp_addr[3],
		lbp_addr[2],
		lbp_addr[1],
		lbp_addr[0] }),
	.SUM({ N76,
		N75,
		N74,
		N73,
		N72,
		N71,
		N70 }),
	.p1(FE_DBTN0_lbp_addr_0));
   GAC_DW01_add_1 add_0_root_sub_0_root_add_83 (.A({ lbp_addr[6],
		lbp_addr[5],
		lbp_addr[4],
		lbp_addr[3],
		lbp_addr[2],
		lbp_addr[1],
		lbp_addr[0] }),
	.B({ N62,
		N62,
		N62,
		N59,
		N58,
		N108,
		n68 }),
	.SUM({ N120,
		N119,
		N118,
		N117,
		N116,
		N115,
		N114 }));
   GAC_DW01_add_0 add_0_root_r392 (.A({ lbp_addr[13],
		lbp_addr[12],
		lbp_addr[11],
		lbp_addr[10],
		lbp_addr[9],
		lbp_addr[8],
		lbp_addr[7] }),
	.B({ N62,
		N62,
		N62,
		N59,
		N58,
		N57,
		n68 }),
	.SUM({ N69,
		N68,
		N67,
		N66,
		N65,
		N64,
		N63 }));
   QDFFRBN \gray_addr_row_reg[6]  (.Q(gray_addr_row[6]),
	.D(n52),
	.CK(clk),
	.RB(n70));
   QDFFRBN \gray_addr_row_reg[5]  (.Q(gray_addr_row[5]),
	.D(n51),
	.CK(clk),
	.RB(n70));
   QDFFRBN \gray_addr_row_reg[2]  (.Q(gray_addr_row[2]),
	.D(n48),
	.CK(clk),
	.RB(n70));
   QDFFRBN \gray_addr_row_reg[1]  (.Q(gray_addr_row[1]),
	.D(n47),
	.CK(clk),
	.RB(n70));
   QDFFRBN \gray_addr_col_reg[5]  (.Q(gray_addr_col[5]),
	.D(n58),
	.CK(clk),
	.RB(n70));
   QDFFRBN \gray_addr_col_reg[4]  (.Q(gray_addr_col[4]),
	.D(n57),
	.CK(clk),
	.RB(n70));
   QDFFRBN \gray_addr_col_reg[1]  (.Q(gray_addr_col[1]),
	.D(n54),
	.CK(clk),
	.RB(n70));
   QDFFRBN \gray_addr_col_reg[0]  (.Q(gray_addr_col[0]),
	.D(n53),
	.CK(clk),
	.RB(n70));
   QDFFRBN \gray_addr_row_reg[4]  (.Q(gray_addr_row[4]),
	.D(n50),
	.CK(clk),
	.RB(n70));
   QDFFRBN \gray_addr_row_reg[3]  (.Q(gray_addr_row[3]),
	.D(n49),
	.CK(clk),
	.RB(n70));
   QDFFRBN \gray_addr_row_reg[0]  (.Q(gray_addr_row[0]),
	.D(n46),
	.CK(clk),
	.RB(n70));
   QDFFRBN \gray_addr_col_reg[6]  (.Q(gray_addr_col[6]),
	.D(n59),
	.CK(clk),
	.RB(n70));
   QDFFRBN \gray_addr_col_reg[3]  (.Q(gray_addr_col[3]),
	.D(n56),
	.CK(clk),
	.RB(n70));
   QDFFRBN \gray_addr_col_reg[2]  (.Q(gray_addr_col[2]),
	.D(n55),
	.CK(clk),
	.RB(n70));
   OR2 U3 (.O(n17),
	.I1(n62),
	.I2(n19));
   INV1S U4 (.O(n65),
	.I(n38));
   INV2 U5 (.O(n67),
	.I(initialize));
   NR2 U6 (.O(n37),
	.I1(n69),
	.I2(n68));
   INV1S U7 (.O(n66),
	.I(n42));
   NR2 U8 (.O(n19),
	.I1(n34),
	.I2(n62));
   INV1S U9 (.O(n62),
	.I(n35));
   AN3B2S U11 (.O(n16),
	.I1(n34),
	.B1(n62),
	.B2(n18));
   INV1S U12 (.O(n60),
	.I(n10));
   INV1S U13 (.O(n5),
	.I(n3));
   INV1S U14 (.O(n61),
	.I(n11));
   INV1S U16 (.O(n6),
	.I(n8));
   MOAI1S U17 (.O(gray_addr[7]),
	.A1(n37),
	.A2(n65),
	.B1(n67),
	.B2(gray_addr_row[0]));
   INV1S U18 (.O(n68),
	.I(cycle[0]));
   INV1S U19 (.O(n69),
	.I(cycle[1]));
   OAI222S U20 (.O(gray_addr[0]),
	.A1(n65),
	.A2(n44),
	.B1(n66),
	.B2(n45),
	.C1(initialize),
	.C2(n64));
   INV1S U21 (.O(n64),
	.I(gray_addr_col[0]));
   XNR2HS U22 (.O(n43),
	.I1(cycle[3]),
	.I2(n69));
   OAI112HS U23 (.O(gray_addr[1]),
	.A1(n40),
	.B1(n41),
	.C1(initialize),
	.C2(n63));
   INV1S U24 (.O(n63),
	.I(gray_addr_col[1]));
   ND3 U25 (.O(n41),
	.I1(n42),
	.I2(n43),
	.I3(cycle[0]));
   ND3 U26 (.O(n40),
	.I1(cycle[1]),
	.I2(n68),
	.I3(n38));
   NR2 U27 (.O(n42),
	.I1(n67),
	.I2(cycle[2]));
   NR2 U28 (.O(n39),
	.I1(n66),
	.I2(cycle[1]));
   AOI22S U29 (.O(n21),
	.A1(FE_DBTN0_lbp_addr_0),
	.A2(n19),
	.B1(N70),
	.B2(n62));
   AOI22S U30 (.O(n20),
	.A1(N114),
	.A2(n16),
	.B1(gray_addr_col[0]),
	.B2(n18));
   AOI22S U31 (.O(n23),
	.A1(N93),
	.A2(n19),
	.B1(N71),
	.B2(n62));
   AOI22S U32 (.O(n22),
	.A1(N115),
	.A2(n16),
	.B1(gray_addr_col[1]),
	.B2(n18));
   AOI22S U33 (.O(n25),
	.A1(N94),
	.A2(n19),
	.B1(N72),
	.B2(n62));
   AOI22S U34 (.O(n24),
	.A1(N116),
	.A2(n16),
	.B1(gray_addr_col[2]),
	.B2(n18));
   AOI22S U35 (.O(n27),
	.A1(N95),
	.A2(n19),
	.B1(N73),
	.B2(n62));
   AOI22S U36 (.O(n26),
	.A1(N117),
	.A2(n16),
	.B1(gray_addr_col[3]),
	.B2(n18));
   AOI22S U51 (.O(n29),
	.A1(N96),
	.A2(n19),
	.B1(N74),
	.B2(n62));
   AOI22S U52 (.O(n28),
	.A1(N118),
	.A2(n16),
	.B1(gray_addr_col[4]),
	.B2(n18));
   AOI22S U70 (.O(n31),
	.A1(N97),
	.A2(n19),
	.B1(N75),
	.B2(n62));
   AOI22S U71 (.O(n30),
	.A1(N119),
	.A2(n16),
	.B1(gray_addr_col[5]),
	.B2(n18));
   AOI22S U72 (.O(n33),
	.A1(N98),
	.A2(n19),
	.B1(N76),
	.B2(n62));
   AOI22S U73 (.O(n32),
	.A1(N120),
	.A2(n16),
	.B1(gray_addr_col[6]),
	.B2(n18));
   ND3 U74 (.O(n1),
	.I1(n34),
	.I2(n35),
	.I3(n36));
   INV1S U75 (.O(n18),
	.I(n1));
   INV1S U76 (.O(n15),
	.I(lbp_addr[4]));
   INV1S U77 (.O(n70),
	.I(reset));
   NR2 U79 (.O(n3),
	.I1(cycle[1]),
	.I2(cycle[0]));
   AO12 U80 (.O(N108),
	.A1(n3),
	.B1(cycle[0]),
	.B2(cycle[1]));
   NR2 U85 (.O(n7),
	.I1(cycle[1]),
	.I2(cycle[0]));
   AO12 U86 (.O(N57),
	.A1(n7),
	.B1(cycle[0]),
	.B2(cycle[1]));
   NR2 U87 (.O(n8),
	.I1(n5),
	.I2(cycle[2]));
   AO12 U88 (.O(N58),
	.A1(n8),
	.B1(n5),
	.B2(cycle[2]));
   NR2 U89 (.O(N62),
	.I1(n6),
	.I2(cycle[3]));
   AO12 U90 (.O(N59),
	.A1(N62),
	.B1(n6),
	.B2(cycle[3]));
   NR2 U92 (.O(n10),
	.I1(lbp_addr[1]),
	.I2(lbp_addr[0]));
   AO12 U93 (.O(N93),
	.A1(n10),
	.B1(lbp_addr[0]),
	.B2(lbp_addr[1]));
   NR2 U94 (.O(n11),
	.I1(n60),
	.I2(lbp_addr[2]));
   AO12 U95 (.O(N94),
	.A1(n11),
	.B1(n60),
	.B2(lbp_addr[2]));
   NR2 U96 (.O(n12),
	.I1(n61),
	.I2(lbp_addr[3]));
   AO12 U97 (.O(N95),
	.A1(n12),
	.B1(n61),
	.B2(lbp_addr[3]));
   ND2 U98 (.O(n13),
	.I1(n12),
	.I2(n15));
   OAI12HS U99 (.O(N96),
	.A1(n13),
	.B1(n12),
	.B2(n15));
   XNR2HS U100 (.O(N97),
	.I1(lbp_addr[5]),
	.I2(n13));
   NR2 U101 (.O(n14),
	.I1(lbp_addr[5]),
	.I2(n13));
   XOR2HS U102 (.O(N98),
	.I1(lbp_addr[6]),
	.I2(n14));
endmodule

module GDM (
	reset, 
	gray_data, 
	lbp_data, 
	cycle, 
	fill_right, 
	fill_down, 
	fill_left, 
	initialize, 
	gray_req, 
	clk_clone1, 
	clk);
   input reset;
   input [7:0] gray_data;
   output [7:0] lbp_data;
   input [3:0] cycle;
   input fill_right;
   input fill_down;
   input fill_left;
   input initialize;
   input gray_req;
   input clk_clone1;
   input clk;

   // Internal wires
   wire CTS_2;
   wire n243;
   wire n244;
   wire n245;
   wire n246;
   wire n247;
   wire n248;
   wire n249;
   wire n250;
   wire n251;
   wire n252;
   wire n253;
   wire n254;
   wire n255;
   wire n256;
   wire n257;
   wire n258;
   wire n259;
   wire n260;
   wire n261;
   wire n262;
   wire n263;
   wire n264;
   wire n265;
   wire n266;
   wire n267;
   wire n268;
   wire n269;
   wire n270;
   wire n271;
   wire n272;
   wire n273;
   wire n274;
   wire n275;
   wire n276;
   wire n277;
   wire n278;
   wire n279;
   wire n280;
   wire n281;
   wire n282;
   wire n283;
   wire n284;
   wire n285;
   wire n286;
   wire n287;
   wire n288;
   wire n289;
   wire n290;
   wire n291;
   wire n292;
   wire n293;
   wire n294;
   wire n295;
   wire n296;
   wire n297;
   wire n298;
   wire n299;
   wire n300;
   wire n301;
   wire n302;
   wire n303;
   wire n304;
   wire n305;
   wire n306;
   wire n307;
   wire n308;
   wire n309;
   wire n310;
   wire n311;
   wire n312;
   wire n313;
   wire n314;
   wire n1;
   wire n2;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n23;
   wire n24;
   wire n25;
   wire n26;
   wire n27;
   wire n28;
   wire n29;
   wire n30;
   wire n31;
   wire n32;
   wire n33;
   wire n34;
   wire n35;
   wire n36;
   wire n37;
   wire n38;
   wire n39;
   wire n40;
   wire n41;
   wire n42;
   wire n43;
   wire n44;
   wire n45;
   wire n46;
   wire n47;
   wire n48;
   wire n49;
   wire n50;
   wire n51;
   wire n52;
   wire n53;
   wire n54;
   wire n55;
   wire n56;
   wire n57;
   wire n58;
   wire n59;
   wire n60;
   wire n61;
   wire n62;
   wire n63;
   wire n64;
   wire n65;
   wire n66;
   wire n67;
   wire n68;
   wire n69;
   wire n70;
   wire n71;
   wire n72;
   wire n73;
   wire n74;
   wire n75;
   wire n76;
   wire n77;
   wire n78;
   wire n79;
   wire n80;
   wire n81;
   wire n82;
   wire n83;
   wire n84;
   wire n85;
   wire n86;
   wire n87;
   wire n88;
   wire n89;
   wire n90;
   wire n91;
   wire n92;
   wire n93;
   wire n94;
   wire n95;
   wire n96;
   wire n97;
   wire n98;
   wire n99;
   wire n100;
   wire n101;
   wire n102;
   wire n103;
   wire n104;
   wire n105;
   wire n106;
   wire n107;
   wire n108;
   wire n109;
   wire n110;
   wire n111;
   wire n112;
   wire n113;
   wire n114;
   wire n115;
   wire n116;
   wire n117;
   wire n118;
   wire n119;
   wire n120;
   wire n121;
   wire n122;
   wire n123;
   wire n124;
   wire n125;
   wire n126;
   wire n127;
   wire n128;
   wire n129;
   wire n130;
   wire n131;
   wire n132;
   wire n133;
   wire n134;
   wire n135;
   wire n136;
   wire n137;
   wire n138;
   wire n139;
   wire n140;
   wire n141;
   wire n142;
   wire n143;
   wire n144;
   wire n145;
   wire n146;
   wire n147;
   wire n148;
   wire n149;
   wire n150;
   wire n151;
   wire n152;
   wire n153;
   wire n154;
   wire n155;
   wire n156;
   wire n157;
   wire n158;
   wire n159;
   wire n160;
   wire n161;
   wire n162;
   wire n163;
   wire n164;
   wire n165;
   wire n166;
   wire n167;
   wire n168;
   wire n169;
   wire n170;
   wire n171;
   wire n172;
   wire n173;
   wire n174;
   wire n175;
   wire n176;
   wire n177;
   wire n178;
   wire n179;
   wire n180;
   wire n181;
   wire n182;
   wire n183;
   wire n184;
   wire n185;
   wire n186;
   wire n187;
   wire n188;
   wire n189;
   wire n190;
   wire n191;
   wire n192;
   wire n193;
   wire n194;
   wire n195;
   wire n196;
   wire n197;
   wire n198;
   wire n199;
   wire n200;
   wire n201;
   wire n202;
   wire n203;
   wire n204;
   wire n205;
   wire n206;
   wire n207;
   wire n208;
   wire n209;
   wire n210;
   wire n211;
   wire n212;
   wire n213;
   wire n214;
   wire n215;
   wire n216;
   wire n217;
   wire n218;
   wire n219;
   wire n220;
   wire n221;
   wire n222;
   wire n223;
   wire n224;
   wire n225;
   wire n226;
   wire n227;
   wire n228;
   wire n229;
   wire n230;
   wire n231;
   wire n232;
   wire n233;
   wire n234;
   wire n235;
   wire n236;
   wire n237;
   wire n238;
   wire n239;
   wire n240;
   wire n241;
   wire n242;
   wire n315;
   wire n316;
   wire n317;
   wire n318;
   wire n319;
   wire n320;
   wire n321;
   wire n322;
   wire n323;
   wire n324;
   wire n325;
   wire n326;
   wire n327;
   wire n328;
   wire n329;
   wire n330;
   wire n331;
   wire n332;
   wire n333;
   wire n334;
   wire n335;
   wire n336;
   wire n337;
   wire n338;
   wire n339;
   wire n340;
   wire n341;
   wire n342;
   wire n343;
   wire n344;
   wire n345;
   wire n346;
   wire n347;
   wire n348;
   wire n349;
   wire n350;
   wire n351;
   wire n352;
   wire n353;
   wire n354;
   wire n355;
   wire n356;
   wire n357;
   wire n358;
   wire n359;
   wire n360;
   wire n361;
   wire n362;
   wire n363;
   wire n364;
   wire n365;
   wire n366;
   wire n367;
   wire n368;
   wire n369;
   wire n370;
   wire n371;
   wire n372;
   wire n373;
   wire n374;
   wire n375;
   wire n376;
   wire n377;
   wire n378;
   wire n379;
   wire n380;
   wire n381;
   wire n382;
   wire n383;
   wire n384;
   wire n385;
   wire n386;
   wire n387;
   wire n388;
   wire n389;
   wire n390;
   wire n391;
   wire n392;
   wire n393;
   wire n394;
   wire n395;
   wire n396;
   wire n397;
   wire n398;
   wire n399;
   wire n400;
   wire n401;
   wire n402;
   wire n403;
   wire n404;
   wire n405;
   wire n406;
   wire n407;
   wire n408;
   wire n409;
   wire n410;
   wire n411;
   wire n412;
   wire n413;
   wire n414;
   wire n415;
   wire n416;
   wire n417;
   wire n418;
   wire n419;
   wire n420;
   wire n421;
   wire n422;
   wire n423;
   wire n424;
   wire n425;
   wire n426;
   wire n427;
   wire n428;
   wire n429;
   wire n430;
   wire n431;
   wire n432;
   wire n433;
   wire n434;
   wire n435;
   wire n436;
   wire n437;
   wire n438;
   wire n439;
   wire n440;
   wire n441;
   wire n442;
   wire n443;
   wire n444;
   wire [7:0] g7;
   wire [7:0] gc;
   wire [7:0] g6;
   wire [7:0] g5;
   wire [7:0] g4;
   wire [7:0] g3;
   wire [7:0] g2;
   wire [7:0] g1;
   wire [7:0] g0;

   MOAI1 FE_RC_4_0 (.O(lbp_data[5]),
	.A1(n342),
	.A2(n343),
	.B1(n164),
	.B2(g5[7]));
   MOAI1 FE_RC_3_0 (.O(lbp_data[7]),
	.A1(n238),
	.A2(n239),
	.B1(n164),
	.B2(g7[7]));
   MOAI1 FE_RC_2_0 (.O(lbp_data[6]),
	.A1(n327),
	.A2(n328),
	.B1(n164),
	.B2(g6[7]));
   BUF8CK CTS_ccl_a_buf_00006 (.O(CTS_2),
	.I(clk));
   QDFFRBN \g4_reg[1]  (.Q(g4[1]),
	.D(n273),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g4_reg[6]  (.Q(g4[6]),
	.D(n268),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g2_reg[6]  (.Q(g2[6]),
	.D(n244),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g4_reg[7]  (.Q(g4[7]),
	.D(n267),
	.CK(clk_clone1),
	.RB(n444));
   QDFFRBN \g2_reg[7]  (.Q(g2[7]),
	.D(n243),
	.CK(clk_clone1),
	.RB(n444));
   QDFFRBN \g0_reg[7]  (.Q(g0[7]),
	.D(n259),
	.CK(clk_clone1),
	.RB(n444));
   QDFFRBN \g4_reg[2]  (.Q(g4[2]),
	.D(n272),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g2_reg[2]  (.Q(g2[2]),
	.D(n248),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g0_reg[2]  (.Q(g0[2]),
	.D(n264),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g0_reg[6]  (.Q(g0[6]),
	.D(n260),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g6_reg[7]  (.Q(g6[7]),
	.D(n299),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g7_reg[6]  (.Q(g7[6]),
	.D(n308),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g7_reg[7]  (.Q(g7[7]),
	.D(n307),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g1_reg[7]  (.Q(g1[7]),
	.D(n251),
	.CK(clk_clone1),
	.RB(n444));
   QDFFRBN \g6_reg[2]  (.Q(g6[2]),
	.D(n304),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g7_reg[2]  (.Q(g7[2]),
	.D(n312),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g1_reg[2]  (.Q(g1[2]),
	.D(n256),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g1_reg[6]  (.Q(g1[6]),
	.D(n252),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g5_reg[6]  (.Q(g5[6]),
	.D(n292),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g5_reg[7]  (.Q(g5[7]),
	.D(n291),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g3_reg[7]  (.Q(g3[7]),
	.D(n283),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g5_reg[2]  (.Q(g5[2]),
	.D(n296),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g3_reg[2]  (.Q(g3[2]),
	.D(n288),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \gc_reg[7]  (.Q(gc[7]),
	.D(n275),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g4_reg[3]  (.Q(g4[3]),
	.D(n271),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g2_reg[3]  (.Q(g2[3]),
	.D(n247),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g0_reg[3]  (.Q(g0[3]),
	.D(n263),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g6_reg[3]  (.Q(g6[3]),
	.D(n303),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g4_reg[4]  (.Q(g4[4]),
	.D(n270),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g2_reg[4]  (.Q(g2[4]),
	.D(n246),
	.CK(clk_clone1),
	.RB(n444));
   QDFFRBN \g4_reg[0]  (.Q(g4[0]),
	.D(n274),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g2_reg[0]  (.Q(g2[0]),
	.D(n250),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g2_reg[1]  (.Q(g2[1]),
	.D(n249),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g0_reg[1]  (.Q(g0[1]),
	.D(n265),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g7_reg[3]  (.Q(g7[3]),
	.D(n311),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \gc_reg[3]  (.Q(gc[3]),
	.D(n279),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g4_reg[5]  (.Q(g4[5]),
	.D(n269),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g2_reg[5]  (.Q(g2[5]),
	.D(n245),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g0_reg[4]  (.Q(g0[4]),
	.D(n262),
	.CK(clk_clone1),
	.RB(n444));
   QDFFRBN \g6_reg[4]  (.Q(g6[4]),
	.D(n302),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g6_reg[0]  (.Q(g6[0]),
	.D(n306),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g0_reg[0]  (.Q(g0[0]),
	.D(n266),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g1_reg[3]  (.Q(g1[3]),
	.D(n255),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g6_reg[1]  (.Q(g6[1]),
	.D(n305),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g5_reg[3]  (.Q(g5[3]),
	.D(n295),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g7_reg[4]  (.Q(g7[4]),
	.D(n310),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g7_reg[0]  (.Q(g7[0]),
	.D(n314),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g7_reg[1]  (.Q(g7[1]),
	.D(n313),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g1_reg[1]  (.Q(g1[1]),
	.D(n257),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g0_reg[5]  (.Q(g0[5]),
	.D(n261),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g6_reg[6]  (.Q(g6[6]),
	.D(n300),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g6_reg[5]  (.Q(g6[5]),
	.D(n301),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \gc_reg[0]  (.Q(gc[0]),
	.D(n282),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g7_reg[5]  (.Q(g7[5]),
	.D(n309),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g1_reg[4]  (.Q(g1[4]),
	.D(n254),
	.CK(clk_clone1),
	.RB(n444));
   QDFFRBN \g5_reg[4]  (.Q(g5[4]),
	.D(n294),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g1_reg[0]  (.Q(g1[0]),
	.D(n258),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g5_reg[0]  (.Q(g5[0]),
	.D(n298),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g3_reg[3]  (.Q(g3[3]),
	.D(n287),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g5_reg[1]  (.Q(g5[1]),
	.D(n297),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g3_reg[1]  (.Q(g3[1]),
	.D(n289),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g1_reg[5]  (.Q(g1[5]),
	.D(n253),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g5_reg[5]  (.Q(g5[5]),
	.D(n293),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g3_reg[4]  (.Q(g3[4]),
	.D(n286),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g3_reg[0]  (.Q(g3[0]),
	.D(n290),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g3_reg[6]  (.Q(g3[6]),
	.D(n284),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \g3_reg[5]  (.Q(g3[5]),
	.D(n285),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \gc_reg[1]  (.Q(gc[1]),
	.D(n281),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \gc_reg[2]  (.Q(gc[2]),
	.D(n280),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \gc_reg[6]  (.Q(gc[6]),
	.D(n276),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \gc_reg[4]  (.Q(gc[4]),
	.D(n278),
	.CK(CTS_2),
	.RB(n444));
   QDFFRBN \gc_reg[5]  (.Q(gc[5]),
	.D(n277),
	.CK(CTS_2),
	.RB(n444));
   NR3H U2 (.O(n1),
	.I1(n188),
	.I2(n89),
	.I3(n166));
   ND2 U3 (.O(n2),
	.I1(n85),
	.I2(n208));
   NR2P U4 (.O(n3),
	.I1(n190),
	.I2(n90));
   OA12 U5 (.O(n4),
	.A1(n85),
	.B1(n83),
	.B2(n84));
   INV1S U6 (.O(n137),
	.I(n85));
   INV1S U7 (.O(n51),
	.I(n169));
   ND2 U10 (.O(n96),
	.I1(n85),
	.I2(n131));
   ND2 U11 (.O(n131),
	.I1(n167),
	.I2(n168));
   ND2 U12 (.O(n208),
	.I1(n91),
	.I2(n168));
   INV1S U13 (.O(n27),
	.I(n56));
   INV1S U16 (.O(n50),
	.I(n4));
   ND3 U23 (.O(n169),
	.I1(n92),
	.I2(n189),
	.I3(n235));
   NR2 U24 (.O(n56),
	.I1(n90),
	.I2(n84));
   OR2 U25 (.O(n5),
	.I1(n166),
	.I2(n90));
   INV1S U26 (.O(n97),
	.I(n5));
   OR3S U27 (.O(n6),
	.I1(n188),
	.I2(n89),
	.I3(n190));
   INV1S U28 (.O(n98),
	.I(n6));
   INV2 U34 (.O(n152),
	.I(gc[4]));
   INV1S U35 (.O(n144),
	.I(gc[2]));
   INV1S U36 (.O(n156),
	.I(gc[5]));
   INV1S U38 (.O(n164),
	.I(gc[7]));
   INV3 U39 (.O(n444),
	.I(reset));
   OAI222S U40 (.O(n314),
	.A1(n23),
	.A2(n24),
	.B1(n25),
	.B2(n26),
	.C1(n27),
	.C2(n28));
   OAI222S U41 (.O(n313),
	.A1(n23),
	.A2(n29),
	.B1(n25),
	.B2(n30),
	.C1(n27),
	.C2(n31));
   INV1S U42 (.O(n29),
	.I(g7[1]));
   OAI222S U43 (.O(n312),
	.A1(n23),
	.A2(n32),
	.B1(n25),
	.B2(n33),
	.C1(n27),
	.C2(n34));
   INV1S U44 (.O(n32),
	.I(g7[2]));
   OAI222S U45 (.O(n311),
	.A1(n23),
	.A2(n35),
	.B1(n25),
	.B2(n36),
	.C1(n27),
	.C2(n37));
   OAI222S U46 (.O(n310),
	.A1(n23),
	.A2(n38),
	.B1(n25),
	.B2(n39),
	.C1(n27),
	.C2(n40));
   OAI222S U47 (.O(n309),
	.A1(n23),
	.A2(n41),
	.B1(n25),
	.B2(n42),
	.C1(n27),
	.C2(n43));
   OAI222S U48 (.O(n308),
	.A1(n23),
	.A2(n44),
	.B1(n25),
	.B2(n45),
	.C1(n27),
	.C2(n46));
   OAI222S U49 (.O(n307),
	.A1(n23),
	.A2(n47),
	.B1(n25),
	.B2(n48),
	.C1(n27),
	.C2(n49));
   NR2 U50 (.O(n25),
	.I1(n50),
	.I2(n51));
   INV1S U51 (.O(n47),
	.I(g7[7]));
   AN2 U52 (.O(n23),
	.I1(n52),
	.I2(n53));
   ND2 U53 (.O(n306),
	.I1(n54),
	.I2(n55));
   AOI22S U54 (.O(n55),
	.A1(g5[0]),
	.A2(n56),
	.B1(g6[0]),
	.B2(n57));
   AOI22S U55 (.O(n54),
	.A1(g7[0]),
	.A2(n50),
	.B1(n1),
	.B2(gray_data[0]));
   ND2 U56 (.O(n305),
	.I1(n58),
	.I2(n59));
   AOI22S U57 (.O(n59),
	.A1(g5[1]),
	.A2(n56),
	.B1(g6[1]),
	.B2(n57));
   AOI22S U58 (.O(n58),
	.A1(g7[1]),
	.A2(n50),
	.B1(n1),
	.B2(gray_data[1]));
   ND2 U59 (.O(n304),
	.I1(n60),
	.I2(n61));
   AOI22S U60 (.O(n61),
	.A1(g5[2]),
	.A2(n56),
	.B1(g6[2]),
	.B2(n57));
   AOI22S U61 (.O(n60),
	.A1(g7[2]),
	.A2(n50),
	.B1(n1),
	.B2(gray_data[2]));
   ND2 U62 (.O(n303),
	.I1(n62),
	.I2(n63));
   AOI22S U63 (.O(n63),
	.A1(g5[3]),
	.A2(n56),
	.B1(g6[3]),
	.B2(n57));
   AOI22S U64 (.O(n62),
	.A1(g7[3]),
	.A2(n50),
	.B1(n1),
	.B2(gray_data[3]));
   ND2 U65 (.O(n302),
	.I1(n64),
	.I2(n65));
   AOI22S U66 (.O(n65),
	.A1(g5[4]),
	.A2(n56),
	.B1(g6[4]),
	.B2(n57));
   AOI22S U67 (.O(n64),
	.A1(g7[4]),
	.A2(n50),
	.B1(n1),
	.B2(gray_data[4]));
   ND2 U68 (.O(n301),
	.I1(n66),
	.I2(n67));
   AOI22S U69 (.O(n67),
	.A1(g5[5]),
	.A2(n56),
	.B1(g6[5]),
	.B2(n57));
   AOI22S U70 (.O(n66),
	.A1(g7[5]),
	.A2(n50),
	.B1(n1),
	.B2(gray_data[5]));
   ND2 U71 (.O(n300),
	.I1(n68),
	.I2(n69));
   AOI22S U72 (.O(n69),
	.A1(g5[6]),
	.A2(n56),
	.B1(g6[6]),
	.B2(n57));
   AOI22S U73 (.O(n68),
	.A1(g7[6]),
	.A2(n50),
	.B1(n1),
	.B2(gray_data[6]));
   ND2 U74 (.O(n299),
	.I1(n70),
	.I2(n71));
   AOI22S U75 (.O(n71),
	.A1(g5[7]),
	.A2(n56),
	.B1(g6[7]),
	.B2(n57));
   ND2 U76 (.O(n57),
	.I1(n72),
	.I2(n53));
   AOI22S U77 (.O(n70),
	.A1(g7[7]),
	.A2(n50),
	.B1(n1),
	.B2(gray_data[7]));
   OAI222S U78 (.O(n298),
	.A1(n26),
	.A2(n73),
	.B1(n74),
	.B2(n75),
	.C1(n4),
	.C2(n28));
   OAI222S U79 (.O(n297),
	.A1(n30),
	.A2(n73),
	.B1(n74),
	.B2(n76),
	.C1(n4),
	.C2(n31));
   INV1S U80 (.O(n31),
	.I(g6[1]));
   INV1S U81 (.O(n76),
	.I(g5[1]));
   OAI222S U82 (.O(n296),
	.A1(n33),
	.A2(n73),
	.B1(n74),
	.B2(n77),
	.C1(n4),
	.C2(n34));
   INV1S U83 (.O(n34),
	.I(g6[2]));
   INV1S U84 (.O(n77),
	.I(g5[2]));
   OAI222S U85 (.O(n295),
	.A1(n36),
	.A2(n73),
	.B1(n74),
	.B2(n78),
	.C1(n4),
	.C2(n37));
   OAI222S U86 (.O(n294),
	.A1(n39),
	.A2(n73),
	.B1(n74),
	.B2(n79),
	.C1(n4),
	.C2(n40));
   OAI222S U87 (.O(n293),
	.A1(n42),
	.A2(n73),
	.B1(n74),
	.B2(n80),
	.C1(n4),
	.C2(n43));
   OAI222S U88 (.O(n292),
	.A1(n45),
	.A2(n73),
	.B1(n74),
	.B2(n81),
	.C1(n4),
	.C2(n46));
   OAI222S U89 (.O(n291),
	.A1(n48),
	.A2(n73),
	.B1(n74),
	.B2(n82),
	.C1(n4),
	.C2(n49));
   INV1S U90 (.O(n49),
	.I(g6[7]));
   INV1S U91 (.O(n82),
	.I(g5[7]));
   AN2 U92 (.O(n74),
	.I1(n86),
	.I2(n53));
   ND2 U93 (.O(n53),
	.I1(n84),
	.I2(n87));
   AO12 U94 (.O(n73),
	.A1(n89),
	.B1(n88),
	.B2(n27));
   ND2 U95 (.O(n88),
	.I1(n91),
	.I2(n92));
   ND2 U96 (.O(n290),
	.I1(n93),
	.I2(n94));
   AOI22S U97 (.O(n94),
	.A1(g3[0]),
	.A2(n95),
	.B1(gc[0]),
	.B2(n96));
   AOI22S U98 (.O(n93),
	.A1(n97),
	.A2(gray_data[0]),
	.B1(n98),
	.B2(g5[0]));
   ND2 U99 (.O(n289),
	.I1(n99),
	.I2(n100));
   AOI22S U100 (.O(n100),
	.A1(g3[1]),
	.A2(n95),
	.B1(gc[1]),
	.B2(n96));
   AOI22S U101 (.O(n99),
	.A1(n97),
	.A2(gray_data[1]),
	.B1(n98),
	.B2(g5[1]));
   ND2 U102 (.O(n288),
	.I1(n101),
	.I2(n102));
   AOI22S U103 (.O(n102),
	.A1(g3[2]),
	.A2(n95),
	.B1(gc[2]),
	.B2(n96));
   AOI22S U104 (.O(n101),
	.A1(n97),
	.A2(gray_data[2]),
	.B1(n98),
	.B2(g5[2]));
   ND2 U105 (.O(n287),
	.I1(n103),
	.I2(n104));
   AOI22S U106 (.O(n104),
	.A1(g3[3]),
	.A2(n95),
	.B1(gc[3]),
	.B2(n96));
   AOI22S U107 (.O(n103),
	.A1(n97),
	.A2(gray_data[3]),
	.B1(n98),
	.B2(g5[3]));
   ND2 U108 (.O(n286),
	.I1(n105),
	.I2(n106));
   AOI22S U109 (.O(n106),
	.A1(g3[4]),
	.A2(n95),
	.B1(gc[4]),
	.B2(n96));
   AOI22S U110 (.O(n105),
	.A1(n97),
	.A2(gray_data[4]),
	.B1(n98),
	.B2(g5[4]));
   ND2 U111 (.O(n285),
	.I1(n107),
	.I2(n108));
   AOI22S U112 (.O(n108),
	.A1(g3[5]),
	.A2(n95),
	.B1(gc[5]),
	.B2(n96));
   AOI22S U113 (.O(n107),
	.A1(n97),
	.A2(gray_data[5]),
	.B1(n98),
	.B2(g5[5]));
   ND2 U114 (.O(n284),
	.I1(n109),
	.I2(n110));
   AOI22S U115 (.O(n110),
	.A1(g3[6]),
	.A2(n95),
	.B1(gc[6]),
	.B2(n96));
   AOI22S U116 (.O(n109),
	.A1(n97),
	.A2(gray_data[6]),
	.B1(n98),
	.B2(g5[6]));
   ND2 U117 (.O(n283),
	.I1(n111),
	.I2(n112));
   AOI22S U118 (.O(n112),
	.A1(g3[7]),
	.A2(n95),
	.B1(gc[7]),
	.B2(n96));
   ND2 U119 (.O(n95),
	.I1(n86),
	.I2(n113));
   AOI22S U120 (.O(n111),
	.A1(n97),
	.A2(gray_data[7]),
	.B1(n98),
	.B2(g5[7]));
   ND2 U121 (.O(n282),
	.I1(n114),
	.I2(n115));
   AOI22S U122 (.O(n115),
	.A1(g4[0]),
	.A2(n96),
	.B1(gc[0]),
	.B2(n116));
   AOI22S U123 (.O(n114),
	.A1(n97),
	.A2(g3[0]),
	.B1(n1),
	.B2(g6[0]));
   ND2 U124 (.O(n281),
	.I1(n117),
	.I2(n118));
   AOI22S U125 (.O(n118),
	.A1(g4[1]),
	.A2(n96),
	.B1(gc[1]),
	.B2(n116));
   AOI22S U126 (.O(n117),
	.A1(g3[1]),
	.A2(n97),
	.B1(n1),
	.B2(g6[1]));
   ND2 U127 (.O(n280),
	.I1(n119),
	.I2(n120));
   AOI22S U128 (.O(n120),
	.A1(g4[2]),
	.A2(n96),
	.B1(gc[2]),
	.B2(n116));
   AOI22S U129 (.O(n119),
	.A1(g3[2]),
	.A2(n97),
	.B1(n1),
	.B2(g6[2]));
   ND2 U130 (.O(n279),
	.I1(n121),
	.I2(n122));
   AOI22S U131 (.O(n122),
	.A1(g4[3]),
	.A2(n96),
	.B1(gc[3]),
	.B2(n116));
   AOI22S U132 (.O(n121),
	.A1(g3[3]),
	.A2(n97),
	.B1(n1),
	.B2(g6[3]));
   ND2 U133 (.O(n278),
	.I1(n123),
	.I2(n124));
   AOI22S U134 (.O(n124),
	.A1(g4[4]),
	.A2(n96),
	.B1(gc[4]),
	.B2(n116));
   AOI22S U135 (.O(n123),
	.A1(g3[4]),
	.A2(n97),
	.B1(n1),
	.B2(g6[4]));
   ND2 U136 (.O(n277),
	.I1(n125),
	.I2(n126));
   AOI22S U137 (.O(n126),
	.A1(g4[5]),
	.A2(n96),
	.B1(gc[5]),
	.B2(n116));
   AOI22S U138 (.O(n125),
	.A1(g3[5]),
	.A2(n97),
	.B1(n1),
	.B2(g6[5]));
   ND2 U139 (.O(n276),
	.I1(n127),
	.I2(n128));
   AOI22S U140 (.O(n128),
	.A1(g4[6]),
	.A2(n96),
	.B1(gc[6]),
	.B2(n116));
   AOI22S U141 (.O(n127),
	.A1(g3[6]),
	.A2(n97),
	.B1(n1),
	.B2(g6[6]));
   ND2 U142 (.O(n275),
	.I1(n129),
	.I2(n130));
   AOI22S U143 (.O(n130),
	.A1(g4[7]),
	.A2(n96),
	.B1(gc[7]),
	.B2(n116));
   ND2 U144 (.O(n116),
	.I1(n72),
	.I2(n113));
   AOI22S U145 (.O(n129),
	.A1(g3[7]),
	.A2(n97),
	.B1(n1),
	.B2(g6[7]));
   ND2 U146 (.O(n274),
	.I1(n132),
	.I2(n133));
   OA222 U147 (.O(n133),
	.A1(n134),
	.A2(n5),
	.B1(n26),
	.B2(n131),
	.C1(n135),
	.C2(n136));
   AOI22S U148 (.O(n132),
	.A1(n51),
	.A2(g7[0]),
	.B1(n137),
	.B2(g5[0]));
   ND2 U149 (.O(n273),
	.I1(n138),
	.I2(n139));
   OA222 U150 (.O(n139),
	.A1(n5),
	.A2(n140),
	.B1(n30),
	.B2(n131),
	.C1(n135),
	.C2(n141));
   AOI22S U151 (.O(n138),
	.A1(n51),
	.A2(g7[1]),
	.B1(n137),
	.B2(g5[1]));
   ND2 U152 (.O(n272),
	.I1(n142),
	.I2(n143));
   OA222 U153 (.O(n143),
	.A1(n5),
	.A2(n144),
	.B1(n33),
	.B2(n131),
	.C1(n135),
	.C2(n145));
   AOI22S U154 (.O(n142),
	.A1(n51),
	.A2(g7[2]),
	.B1(n137),
	.B2(g5[2]));
   ND2 U155 (.O(n271),
	.I1(n146),
	.I2(n147));
   OA222 U156 (.O(n147),
	.A1(n5),
	.A2(n148),
	.B1(n36),
	.B2(n131),
	.C1(n135),
	.C2(n149));
   INV1S U157 (.O(n148),
	.I(gc[3]));
   AOI22S U158 (.O(n146),
	.A1(n51),
	.A2(g7[3]),
	.B1(n137),
	.B2(g5[3]));
   ND2 U159 (.O(n270),
	.I1(n150),
	.I2(n151));
   OA222 U160 (.O(n151),
	.A1(n5),
	.A2(n152),
	.B1(n39),
	.B2(n131),
	.C1(n135),
	.C2(n153));
   AOI22S U161 (.O(n150),
	.A1(n51),
	.A2(g7[4]),
	.B1(n137),
	.B2(g5[4]));
   ND2 U162 (.O(n269),
	.I1(n154),
	.I2(n155));
   OA222 U163 (.O(n155),
	.A1(n5),
	.A2(n156),
	.B1(n42),
	.B2(n131),
	.C1(n135),
	.C2(n157));
   AOI22S U164 (.O(n154),
	.A1(n51),
	.A2(g7[5]),
	.B1(n137),
	.B2(g5[5]));
   ND2 U165 (.O(n268),
	.I1(n158),
	.I2(n159));
   OA222 U166 (.O(n159),
	.A1(n5),
	.A2(n160),
	.B1(n45),
	.B2(n131),
	.C1(n135),
	.C2(n161));
   AOI22S U167 (.O(n158),
	.A1(n51),
	.A2(g7[6]),
	.B1(n137),
	.B2(g5[6]));
   ND2 U168 (.O(n267),
	.I1(n162),
	.I2(n163));
   OA222 U169 (.O(n163),
	.A1(n5),
	.A2(n164),
	.B1(n48),
	.B2(n131),
	.C1(n135),
	.C2(n165));
   AN2 U170 (.O(n135),
	.I1(n52),
	.I2(n113));
   ND2 U171 (.O(n113),
	.I1(n166),
	.I2(n87));
   AOI22S U172 (.O(n162),
	.A1(n51),
	.A2(g7[7]),
	.B1(n137),
	.B2(g5[7]));
   ND2 U173 (.O(n266),
	.I1(n170),
	.I2(n171));
   AOI22S U174 (.O(n171),
	.A1(n98),
	.A2(g3[0]),
	.B1(g0[0]),
	.B2(n172));
   AOI22S U175 (.O(n170),
	.A1(g1[0]),
	.A2(n2),
	.B1(n3),
	.B2(gray_data[0]));
   ND2 U176 (.O(n265),
	.I1(n173),
	.I2(n174));
   AOI22S U177 (.O(n174),
	.A1(g3[1]),
	.A2(n98),
	.B1(g0[1]),
	.B2(n172));
   AOI22S U178 (.O(n173),
	.A1(g1[1]),
	.A2(n2),
	.B1(n3),
	.B2(gray_data[1]));
   ND2 U179 (.O(n264),
	.I1(n175),
	.I2(n176));
   AOI22S U180 (.O(n176),
	.A1(g3[2]),
	.A2(n98),
	.B1(g0[2]),
	.B2(n172));
   AOI22S U181 (.O(n175),
	.A1(g1[2]),
	.A2(n2),
	.B1(n3),
	.B2(gray_data[2]));
   ND2 U182 (.O(n263),
	.I1(n177),
	.I2(n178));
   AOI22S U183 (.O(n178),
	.A1(g3[3]),
	.A2(n98),
	.B1(g0[3]),
	.B2(n172));
   AOI22S U184 (.O(n177),
	.A1(g1[3]),
	.A2(n2),
	.B1(n3),
	.B2(gray_data[3]));
   ND2 U185 (.O(n262),
	.I1(n179),
	.I2(n180));
   AOI22S U186 (.O(n180),
	.A1(g3[4]),
	.A2(n98),
	.B1(g0[4]),
	.B2(n172));
   AOI22S U187 (.O(n179),
	.A1(g1[4]),
	.A2(n2),
	.B1(n3),
	.B2(gray_data[4]));
   ND2 U188 (.O(n261),
	.I1(n181),
	.I2(n182));
   AOI22S U189 (.O(n182),
	.A1(g3[5]),
	.A2(n98),
	.B1(g0[5]),
	.B2(n172));
   AOI22S U190 (.O(n181),
	.A1(g1[5]),
	.A2(n2),
	.B1(n3),
	.B2(gray_data[5]));
   ND2 U191 (.O(n260),
	.I1(n183),
	.I2(n184));
   AOI22S U192 (.O(n184),
	.A1(g3[6]),
	.A2(n98),
	.B1(g0[6]),
	.B2(n172));
   AOI22S U193 (.O(n183),
	.A1(g1[6]),
	.A2(n2),
	.B1(n3),
	.B2(gray_data[6]));
   ND2 U194 (.O(n259),
	.I1(n185),
	.I2(n186));
   AOI22S U195 (.O(n186),
	.A1(g3[7]),
	.A2(n98),
	.B1(g0[7]),
	.B2(n172));
   ND2 U196 (.O(n172),
	.I1(n86),
	.I2(n187));
   OA12 U197 (.O(n86),
	.A1(n189),
	.B1(n91),
	.B2(n188));
   AOI22S U198 (.O(n185),
	.A1(g1[7]),
	.A2(n2),
	.B1(n3),
	.B2(gray_data[7]));
   ND2 U199 (.O(n258),
	.I1(n191),
	.I2(n192));
   AOI22S U200 (.O(n192),
	.A1(g2[0]),
	.A2(n2),
	.B1(g1[0]),
	.B2(n193));
   AOI22S U201 (.O(n191),
	.A1(gc[0]),
	.A2(n1),
	.B1(n3),
	.B2(g0[0]));
   ND2 U202 (.O(n257),
	.I1(n194),
	.I2(n195));
   AOI22S U203 (.O(n195),
	.A1(g2[1]),
	.A2(n2),
	.B1(g1[1]),
	.B2(n193));
   AOI22S U204 (.O(n194),
	.A1(gc[1]),
	.A2(n1),
	.B1(g0[1]),
	.B2(n3));
   ND2 U205 (.O(n256),
	.I1(n196),
	.I2(n197));
   AOI22S U206 (.O(n197),
	.A1(g2[2]),
	.A2(n2),
	.B1(g1[2]),
	.B2(n193));
   AOI22S U207 (.O(n196),
	.A1(gc[2]),
	.A2(n1),
	.B1(g0[2]),
	.B2(n3));
   ND2 U208 (.O(n255),
	.I1(n198),
	.I2(n199));
   AOI22S U209 (.O(n199),
	.A1(g2[3]),
	.A2(n2),
	.B1(g1[3]),
	.B2(n193));
   AOI22S U210 (.O(n198),
	.A1(gc[3]),
	.A2(n1),
	.B1(g0[3]),
	.B2(n3));
   ND2 U211 (.O(n254),
	.I1(n200),
	.I2(n201));
   AOI22S U212 (.O(n201),
	.A1(g2[4]),
	.A2(n2),
	.B1(g1[4]),
	.B2(n193));
   AOI22S U213 (.O(n200),
	.A1(gc[4]),
	.A2(n1),
	.B1(g0[4]),
	.B2(n3));
   ND2 U214 (.O(n253),
	.I1(n202),
	.I2(n203));
   AOI22S U215 (.O(n203),
	.A1(g2[5]),
	.A2(n2),
	.B1(g1[5]),
	.B2(n193));
   AOI22S U216 (.O(n202),
	.A1(gc[5]),
	.A2(n1),
	.B1(g0[5]),
	.B2(n3));
   ND2 U217 (.O(n252),
	.I1(n204),
	.I2(n205));
   AOI22S U218 (.O(n205),
	.A1(g2[6]),
	.A2(n2),
	.B1(g1[6]),
	.B2(n193));
   AOI22S U219 (.O(n204),
	.A1(gc[6]),
	.A2(n1),
	.B1(g0[6]),
	.B2(n3));
   ND2 U220 (.O(n251),
	.I1(n206),
	.I2(n207));
   AOI22S U221 (.O(n207),
	.A1(g2[7]),
	.A2(n2),
	.B1(g1[7]),
	.B2(n193));
   ND2 U222 (.O(n193),
	.I1(n72),
	.I2(n187));
   OA12 U223 (.O(n72),
	.A1(n189),
	.B1(n167),
	.B2(n188));
   INV1S U224 (.O(n167),
	.I(n166));
   AOI22S U225 (.O(n206),
	.A1(gc[7]),
	.A2(n1),
	.B1(g0[7]),
	.B2(n3));
   OR3B2 U226 (.O(n166),
	.I1(cycle[0]),
	.B1(n209),
	.B2(cycle[1]));
   INV1S U227 (.O(n89),
	.I(n189));
   ND2 U228 (.O(n250),
	.I1(n210),
	.I2(n211));
   OA222 U229 (.O(n211),
	.A1(n212),
	.A2(n213),
	.B1(n26),
	.B2(n208),
	.C1(n136),
	.C2(n169));
   INV1S U230 (.O(n26),
	.I(gray_data[0]));
   AOI22S U231 (.O(n210),
	.A1(n3),
	.A2(g1[0]),
	.B1(n137),
	.B2(g3[0]));
   ND2 U232 (.O(n249),
	.I1(n214),
	.I2(n215));
   OA222 U233 (.O(n215),
	.A1(n212),
	.A2(n216),
	.B1(n30),
	.B2(n208),
	.C1(n141),
	.C2(n169));
   INV1S U234 (.O(n141),
	.I(g4[1]));
   INV1S U235 (.O(n30),
	.I(gray_data[1]));
   INV1S U236 (.O(n216),
	.I(g2[1]));
   AOI22S U237 (.O(n214),
	.A1(g1[1]),
	.A2(n3),
	.B1(n137),
	.B2(g3[1]));
   ND2 U238 (.O(n248),
	.I1(n217),
	.I2(n218));
   OA222 U239 (.O(n218),
	.A1(n212),
	.A2(n219),
	.B1(n33),
	.B2(n208),
	.C1(n145),
	.C2(n169));
   INV1S U240 (.O(n145),
	.I(g4[2]));
   INV1S U241 (.O(n33),
	.I(gray_data[2]));
   INV1S U242 (.O(n219),
	.I(g2[2]));
   AOI22S U243 (.O(n217),
	.A1(g1[2]),
	.A2(n3),
	.B1(n137),
	.B2(g3[2]));
   ND2 U244 (.O(n247),
	.I1(n220),
	.I2(n221));
   OA222 U245 (.O(n221),
	.A1(n212),
	.A2(n222),
	.B1(n36),
	.B2(n208),
	.C1(n149),
	.C2(n169));
   INV1S U246 (.O(n36),
	.I(gray_data[3]));
   AOI22S U247 (.O(n220),
	.A1(g1[3]),
	.A2(n3),
	.B1(n137),
	.B2(g3[3]));
   ND2 U248 (.O(n246),
	.I1(n223),
	.I2(n224));
   OA222 U249 (.O(n224),
	.A1(n212),
	.A2(n225),
	.B1(n39),
	.B2(n208),
	.C1(n153),
	.C2(n169));
   INV1S U250 (.O(n39),
	.I(gray_data[4]));
   AOI22S U251 (.O(n223),
	.A1(g1[4]),
	.A2(n3),
	.B1(n137),
	.B2(g3[4]));
   ND2 U252 (.O(n245),
	.I1(n226),
	.I2(n227));
   OA222 U253 (.O(n227),
	.A1(n212),
	.A2(n228),
	.B1(n42),
	.B2(n208),
	.C1(n157),
	.C2(n169));
   INV1S U254 (.O(n42),
	.I(gray_data[5]));
   AOI22S U255 (.O(n226),
	.A1(g1[5]),
	.A2(n3),
	.B1(n137),
	.B2(g3[5]));
   ND2 U256 (.O(n244),
	.I1(n229),
	.I2(n230));
   OA222 U257 (.O(n230),
	.A1(n212),
	.A2(n231),
	.B1(n45),
	.B2(n208),
	.C1(n161),
	.C2(n169));
   INV1S U258 (.O(n45),
	.I(gray_data[6]));
   AOI22S U259 (.O(n229),
	.A1(g1[6]),
	.A2(n3),
	.B1(n137),
	.B2(g3[6]));
   ND2 U260 (.O(n243),
	.I1(n232),
	.I2(n233));
   OA222 U261 (.O(n233),
	.A1(n212),
	.A2(n234),
	.B1(n48),
	.B2(n208),
	.C1(n165),
	.C2(n169));
   INV1S U262 (.O(n92),
	.I(n188));
   INV1S U263 (.O(n165),
	.I(g4[7]));
   INV1S U264 (.O(n168),
	.I(n83));
   INV1S U265 (.O(n91),
	.I(n190));
   INV1S U266 (.O(n48),
	.I(gray_data[7]));
   INV1S U267 (.O(n234),
	.I(g2[7]));
   AN2 U268 (.O(n212),
	.I1(n52),
	.I2(n187));
   ND2 U269 (.O(n187),
	.I1(n190),
	.I2(n87));
   ND2 U270 (.O(n87),
	.I1(n83),
	.I2(n90));
   ND3 U271 (.O(n83),
	.I1(gray_req),
	.I2(n85),
	.I3(fill_right));
   OA12 U272 (.O(n52),
	.A1(n189),
	.B1(n235),
	.B2(n188));
   AO12 U273 (.O(n189),
	.A1(n188),
	.B1(fill_down),
	.B2(gray_req));
   AO12 U274 (.O(n188),
	.A1(n137),
	.B1(n236),
	.B2(gray_req));
   OR2 U275 (.O(n236),
	.I1(fill_left),
	.I2(fill_right));
   INV1S U276 (.O(n235),
	.I(n84));
   ND3 U277 (.O(n84),
	.I1(cycle[0]),
	.I2(n209),
	.I3(cycle[1]));
   AOI22S U278 (.O(n232),
	.A1(g1[7]),
	.A2(n3),
	.B1(n137),
	.B2(g3[7]));
   OR3B2 U279 (.O(n90),
	.I1(fill_right),
	.B1(n85),
	.B2(n237));
   AN2 U280 (.O(n237),
	.I1(gray_req),
	.I2(fill_left));
   ND2 U281 (.O(n85),
	.I1(initialize),
	.I2(gray_req));
   OR3B2 U282 (.O(n190),
	.I1(cycle[1]),
	.B1(n209),
	.B2(cycle[0]));
   NR2 U283 (.O(n209),
	.I1(cycle[2]),
	.I2(cycle[3]));
   NR2 U285 (.O(n239),
	.I1(g7[7]),
	.I2(n164));
   AOI13HS U286 (.O(n238),
	.A1(n315),
	.B1(n240),
	.B2(n241),
	.B3(n242));
   MOAI1S U287 (.O(n315),
	.A1(gc[6]),
	.A2(n316),
	.B1(g7[6]),
	.B2(n317));
   NR2 U288 (.O(n316),
	.I1(g7[6]),
	.I2(n317));
   MOAI1S U289 (.O(n317),
	.A1(n38),
	.A2(n318),
	.B1(n156),
	.B2(g7[5]));
   OAI12HS U290 (.O(n318),
	.A1(n152),
	.B1(n156),
	.B2(g7[5]));
   INV1S U291 (.O(n38),
	.I(g7[4]));
   ND2 U292 (.O(n242),
	.I1(gc[6]),
	.I2(n44));
   INV1S U293 (.O(n44),
	.I(g7[6]));
   OAI22S U294 (.O(n241),
	.A1(n319),
	.A2(gc[5]),
	.B1(n319),
	.B2(n41));
   INV1S U295 (.O(n41),
	.I(g7[5]));
   NR2 U296 (.O(n319),
	.I1(g7[4]),
	.I2(n152));
   OAI112HS U297 (.O(n240),
	.A1(n320),
	.B1(n321),
	.C1(gc[3]),
	.C2(n35));
   ND3 U298 (.O(n321),
	.I1(n322),
	.I2(n144),
	.I3(g7[2]));
   OAI112HS U299 (.O(n320),
	.A1(n323),
	.B1(n322),
	.C1(g7[2]),
	.C2(n144));
   ND2 U300 (.O(n322),
	.I1(gc[3]),
	.I2(n35));
   OAI112HS U301 (.O(n323),
	.A1(n324),
	.B1(n325),
	.C1(gc[1]),
	.C2(n24));
   OAI12HS U302 (.O(n324),
	.A1(g7[1]),
	.B1(g7[0]),
	.B2(n326));
   INV1S U303 (.O(n24),
	.I(g7[0]));
   INV1S U304 (.O(n35),
	.I(g7[3]));
   NR2 U306 (.O(n328),
	.I1(g6[7]),
	.I2(n164));
   AOI13HS U307 (.O(n327),
	.A1(n332),
	.B1(n329),
	.B2(n330),
	.B3(n331));
   MOAI1S U308 (.O(n332),
	.A1(gc[6]),
	.A2(n333),
	.B1(g6[6]),
	.B2(n334));
   NR2 U309 (.O(n333),
	.I1(g6[6]),
	.I2(n334));
   MOAI1S U310 (.O(n334),
	.A1(n40),
	.A2(n335),
	.B1(n156),
	.B2(g6[5]));
   OAI12HS U311 (.O(n335),
	.A1(n152),
	.B1(n156),
	.B2(g6[5]));
   INV1S U312 (.O(n40),
	.I(g6[4]));
   ND2 U313 (.O(n331),
	.I1(gc[6]),
	.I2(n46));
   INV1S U314 (.O(n46),
	.I(g6[6]));
   OAI22S U315 (.O(n330),
	.A1(n336),
	.A2(gc[5]),
	.B1(n336),
	.B2(n43));
   INV1S U316 (.O(n43),
	.I(g6[5]));
   NR2 U317 (.O(n336),
	.I1(g6[4]),
	.I2(n152));
   OAI112HS U318 (.O(n329),
	.A1(n337),
	.B1(n338),
	.C1(gc[3]),
	.C2(n37));
   ND3 U319 (.O(n338),
	.I1(n339),
	.I2(n144),
	.I3(g6[2]));
   OAI112HS U320 (.O(n337),
	.A1(n340),
	.B1(n339),
	.C1(g6[2]),
	.C2(n144));
   ND2 U321 (.O(n339),
	.I1(gc[3]),
	.I2(n37));
   OAI112HS U322 (.O(n340),
	.A1(n341),
	.B1(n325),
	.C1(gc[1]),
	.C2(n28));
   OAI12HS U323 (.O(n341),
	.A1(g6[1]),
	.B1(g6[0]),
	.B2(n326));
   INV1S U324 (.O(n28),
	.I(g6[0]));
   INV1S U325 (.O(n37),
	.I(g6[3]));
   NR2 U327 (.O(n343),
	.I1(g5[7]),
	.I2(n164));
   AOI13HS U328 (.O(n342),
	.A1(n347),
	.B1(n344),
	.B2(n345),
	.B3(n346));
   MOAI1S U329 (.O(n347),
	.A1(gc[6]),
	.A2(n348),
	.B1(g5[6]),
	.B2(n349));
   NR2 U330 (.O(n348),
	.I1(g5[6]),
	.I2(n349));
   MOAI1S U331 (.O(n349),
	.A1(n79),
	.A2(n350),
	.B1(n156),
	.B2(g5[5]));
   OAI12HS U332 (.O(n350),
	.A1(n152),
	.B1(n156),
	.B2(g5[5]));
   INV1S U333 (.O(n79),
	.I(g5[4]));
   ND2 U334 (.O(n346),
	.I1(gc[6]),
	.I2(n81));
   INV1S U335 (.O(n81),
	.I(g5[6]));
   OAI22S U336 (.O(n345),
	.A1(n351),
	.A2(gc[5]),
	.B1(n351),
	.B2(n80));
   INV1S U337 (.O(n80),
	.I(g5[5]));
   NR2 U338 (.O(n351),
	.I1(g5[4]),
	.I2(n152));
   OAI112HS U339 (.O(n344),
	.A1(n352),
	.B1(n353),
	.C1(gc[3]),
	.C2(n78));
   ND3 U340 (.O(n353),
	.I1(n354),
	.I2(n144),
	.I3(g5[2]));
   OAI112HS U341 (.O(n352),
	.A1(n355),
	.B1(n354),
	.C1(g5[2]),
	.C2(n144));
   ND2 U342 (.O(n354),
	.I1(gc[3]),
	.I2(n78));
   OAI112HS U343 (.O(n355),
	.A1(n356),
	.B1(n325),
	.C1(gc[1]),
	.C2(n75));
   OAI12HS U344 (.O(n356),
	.A1(g5[1]),
	.B1(g5[0]),
	.B2(n326));
   INV1S U345 (.O(n75),
	.I(g5[0]));
   INV1S U346 (.O(n78),
	.I(g5[3]));
   MOAI1S U347 (.O(lbp_data[4]),
	.A1(n357),
	.A2(n358),
	.B1(n164),
	.B2(g4[7]));
   NR2 U348 (.O(n358),
	.I1(g4[7]),
	.I2(n164));
   AOI13HS U349 (.O(n357),
	.A1(n362),
	.B1(n359),
	.B2(n360),
	.B3(n361));
   MOAI1S U350 (.O(n362),
	.A1(gc[6]),
	.A2(n363),
	.B1(g4[6]),
	.B2(n364));
   NR2 U351 (.O(n363),
	.I1(g4[6]),
	.I2(n364));
   MOAI1S U352 (.O(n364),
	.A1(n153),
	.A2(n365),
	.B1(n156),
	.B2(g4[5]));
   OAI12HS U353 (.O(n365),
	.A1(n152),
	.B1(n156),
	.B2(g4[5]));
   INV1S U354 (.O(n153),
	.I(g4[4]));
   ND2 U355 (.O(n361),
	.I1(gc[6]),
	.I2(n161));
   INV1S U356 (.O(n161),
	.I(g4[6]));
   OAI22S U357 (.O(n360),
	.A1(n366),
	.A2(gc[5]),
	.B1(n366),
	.B2(n157));
   INV1S U358 (.O(n157),
	.I(g4[5]));
   NR2 U359 (.O(n366),
	.I1(g4[4]),
	.I2(n152));
   OAI112HS U360 (.O(n359),
	.A1(n367),
	.B1(n368),
	.C1(gc[3]),
	.C2(n149));
   ND3 U361 (.O(n368),
	.I1(n369),
	.I2(n144),
	.I3(g4[2]));
   OAI112HS U362 (.O(n367),
	.A1(n370),
	.B1(n369),
	.C1(g4[2]),
	.C2(n144));
   ND2 U363 (.O(n369),
	.I1(gc[3]),
	.I2(n149));
   OAI112HS U364 (.O(n370),
	.A1(n371),
	.B1(n325),
	.C1(gc[1]),
	.C2(n136));
   OAI12HS U365 (.O(n371),
	.A1(g4[1]),
	.B1(g4[0]),
	.B2(n326));
   INV1S U366 (.O(n136),
	.I(g4[0]));
   INV1S U367 (.O(n149),
	.I(g4[3]));
   MOAI1S U368 (.O(lbp_data[3]),
	.A1(n372),
	.A2(n373),
	.B1(n164),
	.B2(g3[7]));
   NR2 U369 (.O(n373),
	.I1(g3[7]),
	.I2(n164));
   AOI13HS U370 (.O(n372),
	.A1(n377),
	.B1(n374),
	.B2(n375),
	.B3(n376));
   MOAI1S U371 (.O(n377),
	.A1(gc[6]),
	.A2(n378),
	.B1(g3[6]),
	.B2(n379));
   NR2 U372 (.O(n378),
	.I1(g3[6]),
	.I2(n379));
   MOAI1S U373 (.O(n379),
	.A1(n380),
	.A2(n381),
	.B1(n156),
	.B2(g3[5]));
   OAI12HS U374 (.O(n381),
	.A1(n152),
	.B1(n156),
	.B2(g3[5]));
   OR2 U375 (.O(n376),
	.I1(n160),
	.I2(g3[6]));
   MOAI1S U376 (.O(n375),
	.A1(n382),
	.A2(gc[5]),
	.B1(n383),
	.B2(g3[5]));
   ND2 U377 (.O(n383),
	.I1(n380),
	.I2(gc[4]));
   INV1S U378 (.O(n380),
	.I(g3[4]));
   NR2 U379 (.O(n382),
	.I1(g3[4]),
	.I2(n152));
   OAI112HS U380 (.O(n374),
	.A1(n385),
	.B1(n386),
	.C1(gc[3]),
	.C2(n384));
   ND3 U381 (.O(n386),
	.I1(n387),
	.I2(n144),
	.I3(g3[2]));
   OAI112HS U382 (.O(n385),
	.A1(n388),
	.B1(n387),
	.C1(g3[2]),
	.C2(n144));
   ND2 U383 (.O(n387),
	.I1(gc[3]),
	.I2(n384));
   OAI112HS U384 (.O(n388),
	.A1(n390),
	.B1(n325),
	.C1(gc[1]),
	.C2(n389));
   OAI12HS U385 (.O(n390),
	.A1(g3[1]),
	.B1(g3[0]),
	.B2(n326));
   INV1S U386 (.O(n389),
	.I(g3[0]));
   INV1S U387 (.O(n384),
	.I(g3[3]));
   MOAI1S U388 (.O(lbp_data[2]),
	.A1(n391),
	.A2(n392),
	.B1(n164),
	.B2(g2[7]));
   NR2 U389 (.O(n392),
	.I1(g2[7]),
	.I2(n164));
   AOI13HS U390 (.O(n391),
	.A1(n396),
	.B1(n393),
	.B2(n394),
	.B3(n395));
   MOAI1S U391 (.O(n396),
	.A1(gc[6]),
	.A2(n397),
	.B1(g2[6]),
	.B2(n398));
   NR2 U392 (.O(n397),
	.I1(g2[6]),
	.I2(n398));
   MOAI1S U393 (.O(n398),
	.A1(n225),
	.A2(n399),
	.B1(n156),
	.B2(g2[5]));
   OAI12HS U394 (.O(n399),
	.A1(n152),
	.B1(n156),
	.B2(g2[5]));
   INV1S U395 (.O(n225),
	.I(g2[4]));
   ND2 U396 (.O(n395),
	.I1(gc[6]),
	.I2(n231));
   INV1S U397 (.O(n231),
	.I(g2[6]));
   OAI22S U398 (.O(n394),
	.A1(n400),
	.A2(gc[5]),
	.B1(n400),
	.B2(n228));
   INV1S U399 (.O(n228),
	.I(g2[5]));
   NR2 U400 (.O(n400),
	.I1(g2[4]),
	.I2(n152));
   OAI112HS U401 (.O(n393),
	.A1(n401),
	.B1(n402),
	.C1(gc[3]),
	.C2(n222));
   ND3 U402 (.O(n402),
	.I1(n403),
	.I2(n144),
	.I3(g2[2]));
   OAI112HS U403 (.O(n401),
	.A1(n404),
	.B1(n403),
	.C1(g2[2]),
	.C2(n144));
   ND2 U404 (.O(n403),
	.I1(gc[3]),
	.I2(n222));
   OAI112HS U405 (.O(n404),
	.A1(n405),
	.B1(n325),
	.C1(gc[1]),
	.C2(n213));
   OAI12HS U406 (.O(n405),
	.A1(g2[1]),
	.B1(g2[0]),
	.B2(n326));
   INV1S U407 (.O(n213),
	.I(g2[0]));
   INV1S U408 (.O(n222),
	.I(g2[3]));
   MOAI1S U409 (.O(lbp_data[1]),
	.A1(n406),
	.A2(n407),
	.B1(n164),
	.B2(g1[7]));
   NR2 U410 (.O(n407),
	.I1(g1[7]),
	.I2(n164));
   AOI13HS U411 (.O(n406),
	.A1(n411),
	.B1(n408),
	.B2(n409),
	.B3(n410));
   MOAI1S U412 (.O(n411),
	.A1(gc[6]),
	.A2(n412),
	.B1(g1[6]),
	.B2(n413));
   NR2 U413 (.O(n412),
	.I1(g1[6]),
	.I2(n413));
   MOAI1S U414 (.O(n413),
	.A1(n414),
	.A2(n415),
	.B1(n156),
	.B2(g1[5]));
   OAI12HS U415 (.O(n415),
	.A1(n152),
	.B1(n156),
	.B2(g1[5]));
   OR2 U416 (.O(n410),
	.I1(n160),
	.I2(g1[6]));
   MOAI1S U417 (.O(n409),
	.A1(n416),
	.A2(gc[5]),
	.B1(n417),
	.B2(g1[5]));
   ND2 U418 (.O(n417),
	.I1(n414),
	.I2(gc[4]));
   INV1S U419 (.O(n414),
	.I(g1[4]));
   NR2 U420 (.O(n416),
	.I1(g1[4]),
	.I2(n152));
   OAI112HS U421 (.O(n408),
	.A1(n419),
	.B1(n420),
	.C1(gc[3]),
	.C2(n418));
   ND3 U422 (.O(n420),
	.I1(n421),
	.I2(n144),
	.I3(g1[2]));
   OAI112HS U423 (.O(n419),
	.A1(n422),
	.B1(n421),
	.C1(g1[2]),
	.C2(n144));
   ND2 U424 (.O(n421),
	.I1(gc[3]),
	.I2(n418));
   OAI112HS U425 (.O(n422),
	.A1(n424),
	.B1(n325),
	.C1(gc[1]),
	.C2(n423));
   OAI12HS U426 (.O(n424),
	.A1(g1[1]),
	.B1(g1[0]),
	.B2(n326));
   INV1S U427 (.O(n423),
	.I(g1[0]));
   INV1S U428 (.O(n418),
	.I(g1[3]));
   MOAI1S U429 (.O(lbp_data[0]),
	.A1(n425),
	.A2(n426),
	.B1(n164),
	.B2(g0[7]));
   NR2 U430 (.O(n426),
	.I1(g0[7]),
	.I2(n164));
   AOI13HS U431 (.O(n425),
	.A1(n430),
	.B1(n427),
	.B2(n428),
	.B3(n429));
   MOAI1S U432 (.O(n430),
	.A1(gc[6]),
	.A2(n431),
	.B1(g0[6]),
	.B2(n432));
   NR2 U433 (.O(n431),
	.I1(g0[6]),
	.I2(n432));
   MOAI1S U434 (.O(n432),
	.A1(n433),
	.A2(n434),
	.B1(n156),
	.B2(g0[5]));
   OAI12HS U435 (.O(n434),
	.A1(n152),
	.B1(n156),
	.B2(g0[5]));
   OR2 U436 (.O(n429),
	.I1(n160),
	.I2(g0[6]));
   INV1S U437 (.O(n160),
	.I(gc[6]));
   MOAI1S U438 (.O(n428),
	.A1(n435),
	.A2(gc[5]),
	.B1(n436),
	.B2(g0[5]));
   ND2 U439 (.O(n436),
	.I1(n433),
	.I2(gc[4]));
   INV1S U440 (.O(n433),
	.I(g0[4]));
   NR2 U441 (.O(n435),
	.I1(g0[4]),
	.I2(n152));
   OAI112HS U442 (.O(n427),
	.A1(n438),
	.B1(n439),
	.C1(gc[3]),
	.C2(n437));
   ND3 U443 (.O(n439),
	.I1(n440),
	.I2(n144),
	.I3(g0[2]));
   OAI112HS U444 (.O(n438),
	.A1(n441),
	.B1(n440),
	.C1(g0[2]),
	.C2(n144));
   ND2 U445 (.O(n440),
	.I1(gc[3]),
	.I2(n437));
   OAI112HS U446 (.O(n441),
	.A1(n443),
	.B1(n325),
	.C1(gc[1]),
	.C2(n442));
   ND2 U447 (.O(n325),
	.I1(n134),
	.I2(n140));
   INV1S U448 (.O(n140),
	.I(gc[1]));
   INV1S U449 (.O(n134),
	.I(gc[0]));
   OAI12HS U450 (.O(n443),
	.A1(g0[1]),
	.B1(g0[0]),
	.B2(n326));
   ND2 U451 (.O(n326),
	.I1(gc[1]),
	.I2(gc[0]));
   INV1S U452 (.O(n442),
	.I(g0[0]));
   INV1S U453 (.O(n437),
	.I(g0[3]));
endmodule

module LAC_DW01_inc_0 (
	A, 
	SUM);
   input [6:0] A;
   output [6:0] SUM;

   // Internal wires
   wire [6:2] carry;

   HA1 U1_1_5 (.S(SUM[5]),
	.C(carry[6]),
	.A(A[5]),
	.B(carry[5]));
   HA1 U1_1_4 (.S(SUM[4]),
	.C(carry[5]),
	.A(A[4]),
	.B(carry[4]));
   HA1 U1_1_3 (.S(SUM[3]),
	.C(carry[4]),
	.A(A[3]),
	.B(carry[3]));
   HA1 U1_1_2 (.S(SUM[2]),
	.C(carry[3]),
	.A(A[2]),
	.B(carry[2]));
   HA1 U1_1_1 (.S(SUM[1]),
	.C(carry[2]),
	.A(A[1]),
	.B(A[0]));
   XOR2HS U1 (.O(SUM[6]),
	.I1(carry[6]),
	.I2(A[6]));
   INV1S U2 (.O(SUM[0]),
	.I(A[0]));
endmodule

module LAC_DW01_inc_1 (
	A, 
	SUM);
   input [6:0] A;
   output [6:0] SUM;

   // Internal wires
   wire [6:2] carry;

   HA1 U1_1_5 (.S(SUM[5]),
	.C(carry[6]),
	.A(A[5]),
	.B(carry[5]));
   HA1 U1_1_4 (.S(SUM[4]),
	.C(carry[5]),
	.A(A[4]),
	.B(carry[4]));
   HA1 U1_1_3 (.S(SUM[3]),
	.C(carry[4]),
	.A(A[3]),
	.B(carry[3]));
   HA1 U1_1_2 (.S(SUM[2]),
	.C(carry[3]),
	.A(A[2]),
	.B(carry[2]));
   HA1 U1_1_1 (.S(SUM[1]),
	.C(carry[2]),
	.A(A[1]),
	.B(A[0]));
   XOR2HS U1 (.O(SUM[6]),
	.I1(carry[6]),
	.I2(A[6]));
   INV1S U2 (.O(SUM[0]),
	.I(A[0]));
endmodule

module LAC (
	reset, 
	lbp_addr, 
	lbp_addr_en, 
	lbp_valid, 
	fill_right, 
	fill_down, 
	fill_left, 
	clk);
   input reset;
   output [13:0] lbp_addr;
   input lbp_addr_en;
   input lbp_valid;
   output fill_right;
   output fill_down;
   output fill_left;
   input clk;

   // Internal wires
   wire N11;
   wire N12;
   wire N13;
   wire N14;
   wire N15;
   wire N16;
   wire N17;
   wire N20;
   wire N21;
   wire N22;
   wire N23;
   wire N24;
   wire N25;
   wire N27;
   wire N28;
   wire N29;
   wire N30;
   wire N31;
   wire N32;
   wire N33;
   wire n30;
   wire n31;
   wire n32;
   wire n33;
   wire n35;
   wire n36;
   wire n37;
   wire n38;
   wire n39;
   wire n40;
   wire n41;
   wire n42;
   wire n43;
   wire n44;
   wire n45;
   wire n46;
   wire n47;
   wire n48;
   wire n49;
   wire n1;
   wire n2;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire n10;
   wire n11;
   wire n12;
   wire n13;
   wire n14;
   wire n15;
   wire n16;
   wire n17;
   wire n18;
   wire n19;
   wire n20;
   wire n21;
   wire n22;
   wire n23;
   wire n24;
   wire n25;

   DFFSBN \lbp_addr_row_reg[0]  (.Q(lbp_addr[7]),
	.QB(n35),
	.D(n49),
	.CK(clk),
	.SB(n25));
   DFFSBN \lbp_addr_col_reg[0]  (.Q(lbp_addr[0]),
	.QB(n30),
	.D(n48),
	.CK(clk),
	.SB(n25));
   LAC_DW01_inc_0 add_47 (.A({ lbp_addr[13],
		lbp_addr[12],
		lbp_addr[11],
		lbp_addr[10],
		lbp_addr[9],
		lbp_addr[8],
		lbp_addr[7] }),
	.SUM({ N33,
		N32,
		N31,
		N30,
		N29,
		N28,
		N27 }));
   LAC_DW01_inc_1 add_40 (.A({ lbp_addr[6],
		lbp_addr[5],
		lbp_addr[4],
		lbp_addr[3],
		lbp_addr[2],
		lbp_addr[1],
		lbp_addr[0] }),
	.SUM({ N17,
		N16,
		N15,
		N14,
		N13,
		N12,
		N11 }));
   QDFFN fill_down_reg (.Q(fill_down),
	.D(n31),
	.CK(clk));
   QDFFN fill_left_reg (.Q(fill_left),
	.D(n33),
	.CK(clk));
   QDFFN fill_right_reg (.Q(fill_right),
	.D(n32),
	.CK(clk));
   QDFFRBN \lbp_addr_row_reg[3]  (.Q(lbp_addr[10]),
	.D(n39),
	.CK(clk),
	.RB(n25));
   QDFFRBN \lbp_addr_row_reg[4]  (.Q(lbp_addr[11]),
	.D(n38),
	.CK(clk),
	.RB(n25));
   QDFFRBN \lbp_addr_row_reg[1]  (.Q(lbp_addr[8]),
	.D(n41),
	.CK(clk),
	.RB(n25));
   QDFFRBN \lbp_addr_row_reg[2]  (.Q(lbp_addr[9]),
	.D(n40),
	.CK(clk),
	.RB(n25));
   QDFFRBN \lbp_addr_row_reg[5]  (.Q(lbp_addr[12]),
	.D(n37),
	.CK(clk),
	.RB(n25));
   QDFFRBN \lbp_addr_row_reg[6]  (.Q(lbp_addr[13]),
	.D(n36),
	.CK(clk),
	.RB(n25));
   QDFFRBN \lbp_addr_col_reg[6]  (.Q(lbp_addr[6]),
	.D(n42),
	.CK(clk),
	.RB(n25));
   QDFFRBN \lbp_addr_col_reg[4]  (.Q(lbp_addr[4]),
	.D(n44),
	.CK(clk),
	.RB(n25));
   QDFFRBN \lbp_addr_col_reg[2]  (.Q(lbp_addr[2]),
	.D(n46),
	.CK(clk),
	.RB(n25));
   QDFFRBN \lbp_addr_col_reg[3]  (.Q(lbp_addr[3]),
	.D(n45),
	.CK(clk),
	.RB(n25));
   QDFFRBN \lbp_addr_col_reg[5]  (.Q(lbp_addr[5]),
	.D(n43),
	.CK(clk),
	.RB(n25));
   QDFFRBN \lbp_addr_col_reg[1]  (.Q(lbp_addr[1]),
	.D(n47),
	.CK(clk),
	.RB(n25));
   INV1S U3 (.O(n12),
	.I(n14));
   INV1S U4 (.O(n7),
	.I(n1));
   INV1S U5 (.O(n8),
	.I(n2));
   INV1S U6 (.O(n6),
	.I(lbp_addr[4]));
   NR2 U7 (.O(n1),
	.I1(lbp_addr[1]),
	.I2(lbp_addr[0]));
   AO12 U8 (.O(N20),
	.A1(n1),
	.B1(lbp_addr[0]),
	.B2(lbp_addr[1]));
   NR2 U9 (.O(n2),
	.I1(n7),
	.I2(lbp_addr[2]));
   AO12 U10 (.O(N21),
	.A1(n2),
	.B1(n7),
	.B2(lbp_addr[2]));
   NR2 U11 (.O(n3),
	.I1(n8),
	.I2(lbp_addr[3]));
   AO12 U12 (.O(N22),
	.A1(n3),
	.B1(n8),
	.B2(lbp_addr[3]));
   ND2 U13 (.O(n4),
	.I1(n3),
	.I2(n6));
   OAI12HS U14 (.O(N23),
	.A1(n4),
	.B1(n3),
	.B2(n6));
   XNR2HS U15 (.O(N24),
	.I1(lbp_addr[5]),
	.I2(n4));
   NR2 U16 (.O(n5),
	.I1(lbp_addr[5]),
	.I2(n4));
   XOR2HS U17 (.O(N25),
	.I1(lbp_addr[6]),
	.I2(n5));
   INV1S U18 (.O(n25),
	.I(reset));
   MUX2 U19 (.O(n49),
	.S(n9),
	.A(lbp_addr[7]),
	.B(N27));
   AO222 U20 (.O(n48),
	.A1(n10),
	.A2(lbp_addr[0]),
	.B1(n30),
	.B2(n11),
	.C1(N11),
	.C2(n12));
   AO222 U21 (.O(n47),
	.A1(n10),
	.A2(lbp_addr[1]),
	.B1(N20),
	.B2(n11),
	.C1(N12),
	.C2(n12));
   AO222 U22 (.O(n46),
	.A1(n10),
	.A2(lbp_addr[2]),
	.B1(N21),
	.B2(n11),
	.C1(N13),
	.C2(n12));
   AO222 U23 (.O(n45),
	.A1(n10),
	.A2(lbp_addr[3]),
	.B1(N22),
	.B2(n11),
	.C1(N14),
	.C2(n12));
   AO222 U24 (.O(n44),
	.A1(n10),
	.A2(lbp_addr[4]),
	.B1(N23),
	.B2(n11),
	.C1(N15),
	.C2(n12));
   AO222 U25 (.O(n43),
	.A1(n10),
	.A2(lbp_addr[5]),
	.B1(N24),
	.B2(n11),
	.C1(N16),
	.C2(n12));
   AO222 U26 (.O(n42),
	.A1(n10),
	.A2(lbp_addr[6]),
	.B1(N25),
	.B2(n11),
	.C1(N17),
	.C2(n12));
   NR2 U27 (.O(n11),
	.I1(n12),
	.I2(n10));
   AOI13HS U28 (.O(n10),
	.A1(n12),
	.B1(lbp_valid),
	.B2(n13),
	.B3(n35));
   MUX2 U29 (.O(n41),
	.S(n9),
	.A(lbp_addr[8]),
	.B(N28));
   MUX2 U30 (.O(n40),
	.S(n9),
	.A(lbp_addr[9]),
	.B(N29));
   MUX2 U31 (.O(n39),
	.S(n9),
	.A(lbp_addr[10]),
	.B(N30));
   MUX2 U32 (.O(n38),
	.S(n9),
	.A(lbp_addr[11]),
	.B(N31));
   MUX2 U33 (.O(n37),
	.S(n9),
	.A(lbp_addr[12]),
	.B(N32));
   MUX2 U34 (.O(n36),
	.S(n9),
	.A(lbp_addr[13]),
	.B(N33));
   OA112 U35 (.O(n9),
	.A1(n14),
	.B1(n16),
	.C1(n15),
	.C2(lbp_addr[7]));
   AN2 U36 (.O(n16),
	.I1(n17),
	.I2(lbp_valid));
   OR3B2 U37 (.O(n14),
	.I1(n18),
	.B1(lbp_valid),
	.B2(lbp_addr[7]));
   MUX2 U38 (.O(n33),
	.S(lbp_valid),
	.A(fill_left),
	.B(n19));
   NR2 U39 (.O(n19),
	.I1(n15),
	.I2(lbp_addr[7]));
   MUX2 U40 (.O(n32),
	.S(lbp_valid),
	.A(fill_right),
	.B(n20));
   NR2 U41 (.O(n20),
	.I1(n35),
	.I2(n18));
   MUX2 U42 (.O(n31),
	.S(lbp_valid),
	.A(fill_down),
	.B(n17));
   MUX2 U43 (.O(n17),
	.S(n30),
	.A(n15),
	.B(n18));
   NR2 U44 (.O(n18),
	.I1(n21),
	.I2(n22));
   ND3 U45 (.O(n22),
	.I1(lbp_addr[5]),
	.I2(lbp_addr[4]),
	.I3(lbp_addr[6]));
   ND3 U46 (.O(n21),
	.I1(lbp_addr[2]),
	.I2(lbp_addr[1]),
	.I3(lbp_addr[3]));
   INV1S U47 (.O(n15),
	.I(n13));
   OR3B2 U48 (.O(n13),
	.I1(lbp_addr[1]),
	.B1(n23),
	.B2(n24));
   NR3 U49 (.O(n24),
	.I1(lbp_addr[4]),
	.I2(lbp_addr[6]),
	.I3(lbp_addr[5]));
   NR2 U50 (.O(n23),
	.I1(lbp_addr[3]),
	.I2(lbp_addr[2]));
endmodule

module DS (
	gray_addr, 
	lbp_addr, 
	lbp_data, 
	gray_addr_qtr, 
	lbp_addr_qtr, 
	lbp_data_qtr, 
	gray_count, 
	lbp_count);
   input [13:0] gray_addr;
   input [13:0] lbp_addr;
   input [7:0] lbp_data;
   output [3:0] gray_addr_qtr;
   output [3:0] lbp_addr_qtr;
   output [1:0] lbp_data_qtr;
   input [1:0] gray_count;
   input [1:0] lbp_count;

   // Internal wires
   wire FE_RN_0_0;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire n10;
   wire n11;
   wire n12;
   wire n13;
   wire n14;
   wire n15;
   wire n16;
   wire n17;
   wire n18;
   wire n19;
   wire n20;
   wire n21;
   wire n22;
   wire n23;
   wire n24;
   wire n25;
   wire n2;
   wire n3;
   wire n4;
   wire n26;
   wire n27;

   AN2 FE_RC_1_0 (.O(FE_RN_0_0),
	.I1(n24),
	.I2(n25));
   ND2 FE_RC_0_0 (.O(gray_addr_qtr[0]),
	.I1(FE_RN_0_0),
	.I2(n23));
   ND2 U35 (.O(n20),
	.I1(gray_addr[9]),
	.I2(n18));
   ND2 U36 (.O(n23),
	.I1(gray_addr[8]),
	.I2(n18));
   AN2 U3 (.O(n2),
	.I1(n20),
	.I2(n21));
   AO222 U4 (.O(lbp_addr_qtr[3]),
	.A1(lbp_addr[7]),
	.A2(n9),
	.B1(lbp_addr[3]),
	.B2(n8),
	.C1(lbp_addr[11]),
	.C2(n10));
   AO222 U5 (.O(lbp_addr_qtr[2]),
	.A1(lbp_addr[6]),
	.A2(n9),
	.B1(lbp_addr[2]),
	.B2(n8),
	.C1(lbp_addr[10]),
	.C2(n10));
   ND2 U6 (.O(gray_addr_qtr[1]),
	.I1(n22),
	.I2(n2));
   ND3 U7 (.O(n21),
	.I1(n26),
	.I2(n27),
	.I3(gray_addr[13]));
   AOI22S U8 (.O(n22),
	.A1(gray_addr[5]),
	.A2(n17),
	.B1(gray_addr[1]),
	.B2(n19));
   ND2 U9 (.O(lbp_addr_qtr[0]),
	.I1(n15),
	.I2(n16));
   ND3 U11 (.O(n24),
	.I1(n26),
	.I2(n27),
	.I3(gray_addr[12]));
   AOI22S U12 (.O(n25),
	.A1(gray_addr[4]),
	.A2(n17),
	.B1(gray_addr[0]),
	.B2(n19));
   ND2 U13 (.O(lbp_addr_qtr[1]),
	.I1(n13),
	.I2(n14));
   AO222 U14 (.O(gray_addr_qtr[2]),
	.A1(gray_addr[6]),
	.A2(n17),
	.B1(gray_addr[10]),
	.B2(n18),
	.C1(gray_addr[2]),
	.C2(n19));
   ND2P U15 (.O(lbp_data_qtr[1]),
	.I1(n5),
	.I2(n6));
   AO222 U16 (.O(gray_addr_qtr[3]),
	.A1(gray_addr[7]),
	.A2(n17),
	.B1(gray_addr[11]),
	.B2(n18),
	.C1(gray_addr[3]),
	.C2(n19));
   ND2P U17 (.O(lbp_data_qtr[0]),
	.I1(n11),
	.I2(n12));
   NR2 U18 (.O(n8),
	.I1(n4),
	.I2(n3));
   NR2 U19 (.O(n19),
	.I1(n27),
	.I2(n26));
   AOI22S U20 (.O(n11),
	.A1(lbp_data[2]),
	.A2(n9),
	.B1(lbp_data[4]),
	.B2(n10));
   AOI22S U21 (.O(n12),
	.A1(lbp_data[6]),
	.A2(n7),
	.B1(lbp_data[0]),
	.B2(n8));
   AOI22S U22 (.O(n5),
	.A1(lbp_data[3]),
	.A2(n9),
	.B1(lbp_data[5]),
	.B2(n10));
   AOI22S U23 (.O(n6),
	.A1(lbp_data[7]),
	.A2(n7),
	.B1(lbp_data[1]),
	.B2(n8));
   AOI22S U24 (.O(n14),
	.A1(lbp_addr[13]),
	.A2(n7),
	.B1(lbp_addr[1]),
	.B2(n8));
   AOI22S U25 (.O(n13),
	.A1(lbp_addr[5]),
	.A2(n9),
	.B1(lbp_addr[9]),
	.B2(n10));
   NR2 U26 (.O(n9),
	.I1(n4),
	.I2(lbp_count[0]));
   NR2 U27 (.O(n10),
	.I1(n3),
	.I2(lbp_count[1]));
   NR2 U28 (.O(n7),
	.I1(lbp_count[0]),
	.I2(lbp_count[1]));
   INV1S U29 (.O(n27),
	.I(gray_count[1]));
   NR2 U30 (.O(n17),
	.I1(n27),
	.I2(gray_count[0]));
   INV1S U31 (.O(n26),
	.I(gray_count[0]));
   NR2 U32 (.O(n18),
	.I1(n26),
	.I2(gray_count[1]));
   AOI22S U33 (.O(n15),
	.A1(lbp_addr[4]),
	.A2(n9),
	.B1(lbp_addr[8]),
	.B2(n10));
   AOI22S U34 (.O(n16),
	.A1(lbp_addr[12]),
	.A2(n7),
	.B1(lbp_addr[0]),
	.B2(n8));
   INV1S U37 (.O(n4),
	.I(lbp_count[1]));
   INV1S U38 (.O(n3),
	.I(lbp_count[0]));
endmodule

module LBP (
	clk, 
	reset, 
	gray_addr_qtr, 
	gray_req, 
	gray_ready, 
	gray_data, 
	lbp_addr_qtr, 
	lbp_valid, 
	lbp_data_qtr, 
	finish);
   input clk;
   input reset;
   output [3:0] gray_addr_qtr;
   output gray_req;
   input gray_ready;
   input [7:0] gray_data;
   output [3:0] lbp_addr_qtr;
   output lbp_valid;
   output [1:0] lbp_data_qtr;
   output finish;

   // Internal wires
   wire CTS_2;
   wire initialize;
   wire gray_addr_en;
   wire lbp_addr_en;
   wire fill_right;
   wire fill_down;
   wire fill_left;
   wire [13:0] lbp_addr;
   wire [1:0] gray_count;
   wire [1:0] lbp_count;
   wire [3:0] cycle;
   wire [13:0] gray_addr;
   wire [7:0] lbp_data;

   BUF6CK CTS_ccl_a_buf_00004 (.O(CTS_2),
	.I(clk));
   FSM finite_state_machine (.reset(reset),
	.gray_ready(gray_ready),
	.gray_req(gray_req),
	.lbp_addr(lbp_addr),
	.lbp_valid(lbp_valid),
	.gray_count(gray_count),
	.lbp_count(lbp_count),
	.cycle(cycle),
	.initialize(initialize),
	.gray_addr_en(gray_addr_en),
	.lbp_addr_en(lbp_addr_en),
	.finish(finish),
	.clk(CTS_2));
   GAC gray_addr_ctrl (.reset(reset),
	.gray_addr(gray_addr),
	.lbp_addr(lbp_addr),
	.cycle(cycle),
	.gray_addr_en(gray_addr_en),
	.initialize(initialize),
	.fill_right(fill_right),
	.fill_down(fill_down),
	.fill_left(fill_left),
	.clk(CTS_2));
   GDM gray_data_matrix (.reset(reset),
	.gray_data(gray_data),
	.lbp_data(lbp_data),
	.cycle(cycle),
	.fill_right(fill_right),
	.fill_down(fill_down),
	.fill_left(fill_left),
	.initialize(initialize),
	.gray_req(gray_req),
	.clk_clone1(CTS_2),
	.clk(clk));
   LAC lbp_addr_ctrl (.reset(reset),
	.lbp_addr(lbp_addr),
	.lbp_addr_en(lbp_addr_en),
	.lbp_valid(lbp_valid),
	.fill_right(fill_right),
	.fill_down(fill_down),
	.fill_left(fill_left),
	.clk(CTS_2));
   DS data_spliter (.gray_addr(gray_addr),
	.lbp_addr(lbp_addr),
	.lbp_data(lbp_data),
	.gray_addr_qtr(gray_addr_qtr),
	.lbp_addr_qtr(lbp_addr_qtr),
	.lbp_data_qtr(lbp_data_qtr),
	.gray_count(gray_count),
	.lbp_count(lbp_count));
endmodule

module LBP_CHIP (
	I_clk, 
	I_reset, 
	O_gray_addr_qtr, 
	O_gray_req, 
	I_gray_ready, 
	I_gray_data, 
	O_lbp_addr_qtr, 
	O_lbp_valid, 
	O_lbp_data_qtr, 
	O_finish);
   input I_clk;
   input I_reset;
   output [3:0] O_gray_addr_qtr;
   output O_gray_req;
   input I_gray_ready;
   input [7:0] I_gray_data;
   output [3:0] O_lbp_addr_qtr;
   output O_lbp_valid;
   output [1:0] O_lbp_data_qtr;
   output O_finish;

   // Internal wires
   wire LTIE_LTIEHI_4_NET;
   wire LTIE_LTIEHI_3_NET;
   wire LTIE_LTIEHI_2_NET;
   wire LTIE_LTIEHI_1_NET;
   wire LTIE_LTIEHI_NET;
   wire clk;
   wire reset;
   wire gray_ready;
   wire [7:0] gray_data;
   wire [3:0] gray_addr_qtr;
   wire gray_req;
   wire [3:0] lbp_addr_qtr;
   wire [1:0] lbp_data_qtr;
   wire lbp_valid;
   wire finish;

   TIE1 LTIE_LTIEHI_4 (.O(LTIE_LTIEHI_4_NET));
   TIE1 LTIE_LTIEHI_3 (.O(LTIE_LTIEHI_3_NET));
   TIE1 LTIE_LTIEHI_2 (.O(LTIE_LTIEHI_2_NET));
   TIE1 LTIE_LTIEHI_1 (.O(LTIE_LTIEHI_1_NET));
   TIE1 LTIE_LTIEHI (.O(LTIE_LTIEHI_NET));
   LBP LBP_chip (.clk(clk),
	.reset(reset),
	.gray_addr_qtr(gray_addr_qtr),
	.gray_req(gray_req),
	.gray_ready(gray_ready),
	.gray_data(gray_data),
	.lbp_addr_qtr(lbp_addr_qtr),
	.lbp_valid(lbp_valid),
	.lbp_data_qtr(lbp_data_qtr),
	.finish(finish));
   XMD PAD_I_clk (.O(clk),
	.I(I_clk));
   XMD PAD_I_reset (.O(reset),
	.I(I_reset));
   XMD PAD_I_gray_ready (.O(gray_ready),
	.I(I_gray_ready));
   XMD PAD_I_gray_data7 (.O(gray_data[7]),
	.I(I_gray_data[7]));
   XMD PAD_I_gray_data6 (.O(gray_data[6]),
	.I(I_gray_data[6]));
   XMD PAD_I_gray_data5 (.O(gray_data[5]),
	.I(I_gray_data[5]));
   XMD PAD_I_gray_data4 (.O(gray_data[4]),
	.I(I_gray_data[4]));
   XMD PAD_I_gray_data3 (.O(gray_data[3]),
	.I(I_gray_data[3]));
   XMD PAD_I_gray_data2 (.O(gray_data[2]),
	.I(I_gray_data[2]));
   XMD PAD_I_gray_data1 (.O(gray_data[1]),
	.I(I_gray_data[1]));
   XMD PAD_I_gray_data0 (.O(gray_data[0]),
	.I(I_gray_data[0]));
   YA2GSD PAD_O_gray_req (.O(O_gray_req),
	.I(gray_req),
	.E(LTIE_LTIEHI_4_NET));
   YA2GSD PAD_O_lbp_valid (.O(O_lbp_valid),
	.I(lbp_valid),
	.E(LTIE_LTIEHI_4_NET));
   YA2GSD PAD_O_finish (.O(O_finish),
	.I(finish),
	.E(LTIE_LTIEHI_4_NET));
   YA2GSD PAD_O_gray_addr_qtr3 (.O(O_gray_addr_qtr[3]),
	.I(gray_addr_qtr[3]),
	.E(LTIE_LTIEHI_NET));
   YA2GSD PAD_O_gray_addr_qtr2 (.O(O_gray_addr_qtr[2]),
	.I(gray_addr_qtr[2]),
	.E(LTIE_LTIEHI_NET));
   YA2GSD PAD_O_gray_addr_qtr1 (.O(O_gray_addr_qtr[1]),
	.I(gray_addr_qtr[1]),
	.E(LTIE_LTIEHI_NET));
   YA2GSD PAD_O_gray_addr_qtr0 (.O(O_gray_addr_qtr[0]),
	.I(gray_addr_qtr[0]),
	.E(LTIE_LTIEHI_1_NET));
   YA2GSD PAD_O_lbp_data_qtr1 (.O(O_lbp_data_qtr[1]),
	.I(lbp_data_qtr[1]),
	.E(LTIE_LTIEHI_2_NET));
   YA2GSD PAD_O_lbp_data_qtr0 (.O(O_lbp_data_qtr[0]),
	.I(lbp_data_qtr[0]),
	.E(LTIE_LTIEHI_2_NET));
   YA2GSD PAD_O_lbp_addr_qtr3 (.O(O_lbp_addr_qtr[3]),
	.I(lbp_addr_qtr[3]),
	.E(LTIE_LTIEHI_2_NET));
   YA2GSD PAD_O_lbp_addr_qtr2 (.O(O_lbp_addr_qtr[2]),
	.I(lbp_addr_qtr[2]),
	.E(LTIE_LTIEHI_3_NET));
   YA2GSD PAD_O_lbp_addr_qtr1 (.O(O_lbp_addr_qtr[1]),
	.I(lbp_addr_qtr[1]),
	.E(LTIE_LTIEHI_3_NET));
   YA2GSD PAD_O_lbp_addr_qtr0 (.O(O_lbp_addr_qtr[0]),
	.I(lbp_addr_qtr[0]),
	.E(LTIE_LTIEHI_3_NET));
endmodule

